### ISSUE TITLE
Env Builder maxReaders Default Value Different Than LMDB

### ISSUE THREAD

**Issue by seancarroll** [lmdbjava/lmdbjava#102]
LMDB's default is 126 however maxReaders in Env.Builder default is 1. Is there a reason why this shouldn't match LMDB's default?

**Comment by benalexau** [comment]
There was a related discussion in issue #65 about this. My [closing comment](https://github.com/lmdbjava/lmdbjava/issues/65#issuecomment-396766134) was we should set the value to 126. Thanks for raising this ticket; I'll make the change in the code before the next release. Please feel free to submit a PR if you wish.

**Comment by benalexau** [comment]
Defaults now applied as of commit 7cf8f02fbebc3cb750311b2bd4d1b5180ea8ac7d
