### ISSUE TITLE
API for resizing Env's mapsize

### ISSUE THREAD

**Issue by bluegol** [lmdbjava/lmdbjava#104]
According to lmdb's doc, it seems that Env's mapsize can be resized after open as long as there's no active write transaction. http://www.lmdb.tech/doc/group__mdb.html#gaa2506ec8dab3d969b0e609cd82e619e5 "It may be called at later times if no transactions are active in this process."

However lmdbjava doesn't seem to have this capability. Please consider adding an API for this.

**Comment by altesse** [comment]
If I may, most humbly, I will submit a pull request for this feature from [my fork](https://github.com/altesse/lmdbjava) , since I need it too.
