### ISSUE TITLE
Database created by Python, but can't read key from Java

### ISSUE THREAD

**Issue by fangkuann** [lmdbjava/lmdbjava#109]
Hi, I created a database usign lmdb-python, the code is like 

```for line in open(file_path):
    count += 1
    if count > 10000: break
    try:
        with env.begin(write=True) as txn:
            line = line.strip()
            fields = line.split('\t')
            key = fields[0]
            value = "\t".join(fields[1:])
            txn.put(str(key), value)
            if count % step == 0:
                taken = time.time()*1000 - tn
                print "Inserted: %d rows at %.3f vals/sec"%(count, float(step) * 1000 / taken)
                tn = time.time() * 1000
                #txn.commit()
    except lmdb.BadValsizeError:
        sys.stderr.write("lmdb.BadValsizeError\n")
        continue
```

I can read values properly in a python read interface;
I need to query keys in a java application;
but I found using java's ByteBuffer, I cannot extract values given keys written in python codes; Is there any methods can java read python-generated lmdb database?

**Comment by vladp** [comment]
It would be helpful to see your java code snippet where you read the data.

You should also compare your java code with the Tutorial , where the data is being read in.

For example line 124 of this
https://github.com/lmdbjava/lmdbjava/blob/master/src/test/java/org/lmdbjava/TutorialTest.java

There should be no problem reading the data from Java even if db was created in Python (obviously also check that the data is there).

**Comment by benalexau** [comment]
I agree with @vladp there should not be any difficulty reading LMDB databases created in another language.

I notice the Python `txn.commit()` is commented. No data will be saved unless you commit.

You might like to try the [LMDB Tools](http://www.lmdb.tech/doc/tools.html) to see if they can read the database you created in Python. Alternately, try iterating over the entire table and outputting the keys. For example [tutorial method 4](https://github.com/lmdbjava/lmdbjava/blob/master/src/test/java/org/lmdbjava/TutorialTest.java#L301) shows how to iterate.

**Comment by benalexau** [comment]
I'll close this given there were no further replies. Happy to reopen if extra information is available.

**Comment by xtuyaowu** [comment]
i have a question: create by java , but can not read from python!
