### ISSUE TITLE
How to boost performance

### ISSUE THREAD

**Issue by pranasblk** [lmdbjava/lmdbjava#119]
I'm testing Java driver with Agrona:0.9.1 and lmdbjava:0.6.3 and getting quite good lookup speed. Are there options to improve int => int map performance. My first attempt:

`

public class LMDBAgronaTest {
  private static final String DB_NAME = "kv";
  private static final long MAX_ENTRIES = 1_000_000;
  private static final int ONE_K = 1_024;
  private static final int MAX_ENTRY = 4 * ONE_K;

  @Rule
  public final TemporaryFolder tmp = new TemporaryFolder();

  // DB state
  private Env<DirectBuffer> env;
  private Dbi<DirectBuffer> db;
  private MutableDirectBuffer key;
  private MutableDirectBuffer val;

  @Before
  public void setUp() throws IOException {
    System.setProperty(Env.DISABLE_CHECKS_PROP, String.valueOf(true));
    final File path = tmp.newFolder();
    env = create(PROXY_DB)
        .setMapSize(MAX_ENTRY * MAX_ENTRIES * 3)
        .setMaxDbs(1)
        .open(path, MDB_NOMETASYNC, MDB_NOSYNC);
    db = env.openDbi(DB_NAME, MDB_CREATE);
    key = new UnsafeBuffer(allocateDirect(4));
    val = new UnsafeBuffer(allocateDirect(4));
  }

  @After
  public void tearDown() {
    out.println("Before close: " + new Date());
    db.close();
    env.close();
    out.println("After close: " + new Date());
  }

  @Test
  public void nativeBuffersNoFlushOrderedKeys() {

    // Write one by one
    out.println("Begin insert: " + new Date());
    for (int i = 0; i < MAX_ENTRIES; ++i) {
      val.putInt(0, i);
      key.putInt(0, i);
      db.put(key, val);
    }

    // Read one by one
    out.println("Begin lookup: " + new Date());
    final Txn<DirectBuffer> t = env.txnRead();
    t.reset();
    for (int i = 0; i < MAX_ENTRIES; ++i) {
      t.renew();
      key.putInt(0, i);
      final DirectBuffer result = db.get(t, key);
      assertNotNull(result);
      assertEquals(i, result.getInt(0));
      t.reset();
    }
  }
}

`

> Begin insert: Fri Feb 15 12:26:40 AEDT 2019
> Begin lookup: Fri Feb 15 12:27:05 AEDT 2019
> Before close: Fri Feb 15 12:27:05 AEDT 2019
> After close: Fri Feb 15 12:27:05 AEDT 2019

- How do you estimate map size? Looks like 4k * MAX_ENTRIES is not sufficient ..
- Is there best practice document for threading in java env.?
- Has someone experience in serializing using Kryo and storing in LMLDB Java (e.g. type of buffer selection)?

I'm total newbie in LMDB and advices would be very welcome. I'm trying gradually extend value to store bloated java objects instead of currently int.

Thanks
Pranas
-

**Comment by benalexau** [comment]
Your code on my machine resulted in about 7 seconds to complete the writes:

```
Begin insert: Fri Feb 15 12:57:25 AEDT 2019
Begin lookup: Fri Feb 15 12:57:32 AEDT 2019
Before close: Fri Feb 15 12:57:32 AEDT 2019
After close: Fri Feb 15 12:57:32 AEDT 2019
```

I then modified the write operation to use a single write transaction:

```java
    // Write one by one
    out.println("Begin insert: " + new Date());
    try (final Txn<DirectBuffer> t = env.txnWrite()) {
      for (int i = 0; i < MAX_ENTRIES; ++i) {
        val.putInt(0, i);
        key.putInt(0, i);
        db.put(t, key, val);
      }
      t.commit();
    }
```

This resulted in the writes now taking just one second:

```
Begin insert: Fri Feb 15 13:01:39 AEDT 2019
Begin lookup: Fri Feb 15 13:01:40 AEDT 2019
Before close: Fri Feb 15 13:01:40 AEDT 2019
After close: Fri Feb 15 13:01:40 AEDT 2019
```

Always use a single transaction where you can, especially for writes.

My next observation is specify the byte order, such as `key.putInt(0, i, ByteOrder.BIG_ENDIAN)`. Using Big Endian will ensure the keys will be physically written to disk (and subsequently read back from disk) in the same order as your `for` loop is writing (or reading) them. Little Endian means the on-disk "sorted" layout differs from the `int` order. So if you pulled the data back with an iterator you would not go from 0 to 1,000,000. In addition LMDB will not consider the keys naturally sorted at the time of the original write, so the pages will be split to allow for future keys to be inserted. In general, use Big Endian for the numeric portion of keys unless you have a specific reason not to.

One specific reason by the way may be that you are storing `long` keys. If storing `long`s you can use `DbiFlags.MDB_INTEGERKEY` when producing the `Dbi` so LMDB understands you are storing a 64-bit numeric key. But you're storing `int`s above, so the general advice to use Big Endian applies.

> How do you estimate map size? Looks like 4k * MAX_ENTRIES is not sufficient

In terms of the map size estimate, this is typically significantly greater than the size you ever intend to store. On Unix-like platforms the physical disk consumption only increases as the real data grows, not the map size. You may prefer to select a map size equal to the current size plus an allowance for growth during the current execution. You can increase the map size later on. It isn't fixed for the life of the database (only the `Env` instance).

If you wish to size it more accurately, you need to factor in that LMDB stores data in pages. I discuss this in the [LmdbJava Benchmark report](https://github.com/lmdbjava/benchmarks/blob/master/results/20160710/README.md#test-2-determine-24816-kb-byte-values) so won't repeat it here. Suffice to say if storing `int` keys with `int` values it would be less expensive to either pack them into a larger unit (eg if you have a natural application-specific array and could store at that array granularity) or store them as `long` keys and `long` values and rely on `DbiFlags` such as duplicate `MDB_DUPFIXED`. That way LMDB can make page size optimisations as it knows the fixed size of each entry (key and value).

> Is there best practice document for threading in java env?

The most important transaction consideration is LmdbJava is not itself transactional. It expects the developer to understand the LMDB transactional model applies. This is multi-process, not simply Java-only transactions. In a nutshell if any transaction in any process acquires a write transaction to a specific LMDB database, two things will happen:

1. Any other request to obtain a write transaction will block that requestor's control flow.
2. Any read transactions occurring concurrently with a write transaction will see their own isolated snapshot of the data (ie usual MVCC) *but* such read transactions will cause the LMDB data file to grow.

Like anything else, it's about trade-offs. If you are running in a single process you may as well use Java-side threading primitives to prevent LMDB from being asked to commence multiple concurrent write transactions. That way you have better control over what is going on (eg you can use a timeout etc). As for read transactions you have to decide if you want to just block them from happening so the file doesn't grow, or you actually need read transactions and a write transaction to operate concurrently and accept the growth.

Personally most of my LMDB applications open one very long-lived transaction and it's used for both reads and writes. But my applications handle massive amounts of data and primarily as batches. The change of each calendar day offers a natural boundary to commit the long-lived transaction and move to a new calendar day. That also simplifies operational considerations (like tape backup, rebuilding after a failure etc). This would obviously be unsuitable for many situations though, such as if LMDB was used as the sole system of record and as such its full ACID capabilities were required.

> Has someone experience in serializing using Kryo and storing in LMLDB Java (e.g. type of buffer selection)?

You can serialize with any library you like. I usually use [Simple Binary Encoding](https://github.com/real-logic/simple-binary-encoding) for values and custom (almost always code-generated) byte arrays for keys. The custom byte arrays for keys is necessary so you can expressly control for iterator sort ordering, especially where composite keys are required. For example if you want a key to store say someone's date of birth and then customer number (to distinguish customers with the same date of birth), I would encode that as a 16 byte key containing the two Big Endian `long`s.

Good luck with LmdbJava. LMDB is extremely powerful and reliable, but it has a learning curve. Feel free to add any more questions and we'll be able to help.

**Comment by pranasblk** [comment]
Thanks, your know how helps a lot! I'll add micro bache of writes.

If I understand correctly it would be OK Multiplexing multiple writers to single writer and RO file reader locked by Java locks. 
Would it be possible to use Stamped locks for reading (options MDB_RDONLY_ENV, MDB_NOLOCK) i.e. is memory (heap or native) is modified during read operation?

**Comment by JulienBe** [comment]
Thanks for your detailed answer ! :+1:
