### ISSUE TITLE
malloc error

### ISSUE THREAD

**Issue by rrwright** [lmdbjava/lmdbjava#122]
I'm beginning to experiment with this project—and am likely doing plenty of things wrong—but encountered a cryptic `malloc` error and program crash after using this library successfully for several experiments. I'm posting what information I have in case this experience represents a stability bug in the code. If it only reflects me using the library incorrectly, my apologies along with appreciation for any tips on better usage.

While ingesting data into an lmdbjava system, it worked successfully for the first 340,000 items ingested, then hard crashed with the following error:
```
java(7179,0x70001ee7e000) malloc: *** error for object 0x70001ee7cf70: pointer being freed was not allocated
java(7179,0x70001e275000) malloc: *** error for object 0x70001ee7cf70: pointer being freed was not allocated
java(7179,0x70001ee7e000) malloc: *** set a breakpoint in malloc_error_break to debug
java(7179,0x70001e275000) malloc: *** set a breakpoint in malloc_error_break to debug
```

There was no other error message; no stack trace, etc. Before the error, everything seemed to be working fine. Running this system with a different key/value store (instead of lmdbjava) has worked successfully for a very long time. 

The program terminated immediately and ungracefully after printing this message. Some of the data on disk was created during an earlier run of my application which ingested some data (~300,000 key/value pairs) before being shut down normally. Then I restarted and ran the same ingest. My relevant code (in Scala) is below:

```
val env = org.lmdbjava.Env
    .create()
    .setMapSize(3000485760L)
    .setMaxDbs(32)
    .setMaxReaders(1024)
    .open(new File(path), MDB_WRITEMAP, MDB_NOSYNC, MDB_NOLOCK)

  val db = env.openDbi("foo", org.lmdbjava.DbiFlags.MDB_CREATE)

def persistSnapshot(id: MyID, atTime: Milliseconds, state: Array[Byte]): Future[Unit] = {
    val idBb = ByteBuffer.allocateDirect(id.array.length)
    idBb.put(id.array).flip()
    val stateBb = ByteBuffer.allocateDirect(state.length)
    stateBb.put(state).flip()
    Future(db.put(idBb, stateBb))
  }

  def getLatestSnapshot(id: MyID, upToTime: Option[Milliseconds]): Future[Option[(Milliseconds, Array[Byte])]] = Future{
    val tx = env.txnRead()
    val idBb: ByteBuffer = ByteBuffer.allocateDirect(id.array.length)
    idBb.put(id.array).flip()
    val result = Option(db.get(tx, idBb)).map(r => 0L -> r.array())
    tx.close()
    result
  }
```

**Comment by benalexau** [comment]
It's hard to know what's wrong here. A few queries:

* What is the code trying to do, at a high level? It's not immediately obvious to me as it seems some code is absent (eg `atTime` in `persistSnapshot` is used for what?).
* Which operating system and Java version you are using? Did you try it on another operating system and Java version?
* Which version of LmdbJava is being used?
* Can you try writing the code in ordinary Java as a unit test and posting that so I can run it locally?
* If you delete the database and re-run does it always fail, and if so, at the same stage (ie is it deterministic when it fails)?

**Comment by rrwright** [comment]
The `persistSnapshot` and `getLatestSnapshot` functions only save and retrieve a value (the `Array[Byte]`), given a key (`MyID`). So this code is a write-heavy workload that is mostly writing key/value pairs, but with an occassional (rare) call to get a value given the key.

OS = macOS 10.14.3
Java version = Oracle JVM, build 1.8.0_131-b11
I did not try it on any other OS or Java version.

LMBD version = 0.6.3

This behavior is not regularly reproducible. Multiple runs of the same code/data were unable to reproduce the problem, when deleting the data and not.

Is there any feature for extra logging or debug information that I could turn on? The brief error log I have (posted above) is the only information about what could be wrong—and it suggests to me that there is some subtle-but-critical bug in the use of unsafe methods.

I realize how annoying it is to get a non-reproducible bug report; apologies! But on the surface, it seems like there is a bug in the unsafe code which will affect decisions about whether to use/trust this library. Alternatively, if we could pin this down to a JVM bug or some other environmental cause, that might better instill confidence.

**Comment by benalexau** [comment]
Thanks for the extra information.

The most "unusual" part of your environment is MacOS. Most past issue reporters have been using LmdbJava on Linux or Windows. So assuming your code is OK, it is possible that you have encountered a bug with how LmdbJava (or the embedded LMDB library) behave on MacOS, or perhaps with that particular JVM.

There is no additional logging available unfortunately.

My suggestions would be as follows, in order of ease:

1. Try cloning the LmdbJava repository and repeatedly running the tests to see if they ever crash (I'd suggest running a shell script overnight that loops indefinitely unless it encounters a non-zero exit from `mvn test`)
2. Try to use `ByteBufferProxy.PROXY_SAFE` instead of `PROXY_OPTIMAL` in your code
3. Try to upgrade to Java 11
4. Try your code with a different operating system
5. Try to port your code to Java so I can give it a try (I can borrow my wife's MacOS laptop)

Hope this helps.

**Comment by rrwright** [comment]
Just a quick note to say that re-running my original example does reproduce the same error at what appears to be the point ding data ingest. (Note, this is without trying the suggestions you mentioned—just wanted to pass along that I can reproduce the error.)

**Comment by rrwright** [comment]
Being able to reproduce the error, I trial-and-error'ed my way through to what I believe is a solution/work-around to this problem. I believe the use of `MDB_NOLOCK` is what caused the `malloc` error. I had assumed my application would properly manage access—or that I understand the implementation of locking in lmdbjava—but that was probably incorrect. When running without the `MDB_NOLOCK` option, the problem does not occur. If possible, it would nice to have a better error message in this failing case.

Thank you for your input, and your work in creating this library! You can resolve this issue whenever you please. All the best!

**Comment by benalexau** [comment]
Very pleased that you found a solution!

There isn't much we can do on the Java side to catch a native library `SIGSEGV`. I think there's probably more utility in providing an "environment verifier" within LmdbJava that executes a defined sequence of write-then-read operations with successively larger keys, values, transaction sizes and user-nominated durations. That way when people suspecting platform bugs can invoke a local method to provide more confidence it's not platform-specific.

**Comment by benalexau** [comment]
I just added a `Verifier` class (see issue #124)for the `ByteBuffer` buffer type. 

You may like to try the 0.6.4-SNAPSHOT (see the [Snapshot Repository](https://oss.sonatype.org/content/repositories/snapshots/org/lmdbjava/lmdbjava/)) with `PROXY_OPTIMAL` and `PROXY_SAFE` to get some extra confidence things are working OK on your platform. 

BTW thanks for logging this ticket, as it prompted the development of the `Verifier`. Hopefully it'll save folks time in the future.
