### ISSUE TITLE
ByteArrayProxy potentially causing JRE crash on Windows

### ISSUE THREAD

**Issue by ChrisTrenkamp** [lmdbjava/lmdbjava#123]
I've swapped lmdbjni with lmdbjava in one of my projects, using the ByteArrayProxy class, and I'm experiencing random crashes with the JRE.  I'm running on Windows 10, and opening the environment with MDB_NOTLS and MDB_NOREADAHEAD.  It crashes on mdb_get operations.

I think it has something to do with the ByteArrayProxy class because in an experimental fork in the same codebase, it is also using lmdbjava, but is instead using the DirectBufferProxy class.  I have not run into any JRE crashes in this fork.

I've tried using 0.6.0-0.6.3 and all are experiencing crashes.  I cannot reliably reproduce this problem.  It seems to occur randomly.

**Comment by benalexau** [comment]
As you're on Windows perhaps https://github.com/lmdbjava/lmdbjava/issues/121 is worth a look? Could you try `getAddress` in a locally-compiled version of LmdbJava with `PROXY_SAFE` and report back if it makes a difference?

**Comment by benalexau** [comment]
I just added a `Verifier` class (see issue #124) for the `ByteBuffer` buffer type. This executes an extensive test workload for a user-defined duration and should illustrate if there are any issues with the JVM / operating system combination you're using.

As such can you please try the 0.6.4-SNAPSHOT (see the [Snapshot Repository](https://oss.sonatype.org/content/repositories/snapshots/org/lmdbjava/lmdbjava/)). You can have a look in the updated [TutorialTest](https://github.com/lmdbjava/lmdbjava/blob/master/src/test/java/org/lmdbjava/TutorialTest.java) for an example of how to run the `Verifier`.

Hope this helps.

**Comment by ChrisTrenkamp** [comment]
Hm, I just tried to reproduce the problem and cannot do it.  I probably did something wrong.

Closing.  Thanks for taking a look at this.

**Comment by ChrisTrenkamp** [comment]
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 2397  com.kenai.jffi.Foreign.invokeArrayReturnInt(JJ[B)I (0 bytes) @ 0x0000027e85f1cedd [0x0000027e85f1ce80+0x5d]
J 4397 C2 org.lmdbjava.Dbi.get(Lorg/lmdbjava/Txn;Ljava/lang/Object;)Ljava/lang/Object; (80 bytes) @ 0x0000027e862e7ba8 [0x0000027e862e7820+0x388]
```

Okay, I can reproduce this again.  What's strange is sometimes the JRE just simply segfaults, other times it produces a crash log.  Sometimes the crash log is on a get, sometimes it's on a put.  Sometimes it crashes immediately, sometimes the program succeeds.  I am completely dumbfounded.  The codebase has been running on lmdbjni for two years with no problems.  Now that it's lmdbjava, using the ByteArrayProxy, and doing an API update, this behavior started occuring.  

Here's what I do know:
* Using ByteBufferProxy.SAFE_PROXY makes it crash less frequently.
* Turning the number of threads in the program to 1, and therefore, the number of workers accessing the database to 1, seems to alleviate the crashes as well, though I don't know for sure.

**Comment by ChrisTrenkamp** [comment]
```
J 3142  com.kenai.jffi.Foreign.invokeArrayReturnInt(JJ[B)I (0 bytes) @ 0x000001988be2ba1d [0x000001988be2b9c0+0x5d]
```
This method is always at the top of the stack in the crash logs.  Any idea's what the problem might be?

**Comment by ChrisTrenkamp** [comment]
I ran some tests with the different proxies.  I have an application that runs for about 5 minutes.  Each run makes hundreds of thousands of get and put operations.  The environment flags it uses is NOTLS and NOREADAHEAD.  I ran three different tests using the different proxies.  I recorded the results of the various get operations.   If no errors occured, it's a success.  If a null or corrupt operation occures, it's a failure. All of the get's should return a valid result.  However, this is what I found:

ByteBufferProxy.PROXY_OPTIMAL - 100 runs.  95 successes. 4 had a get operations that returned null.  1 had a get operation that was corrupt.
ByteBufferProxy.PROXY_SAFE - 100 runs.  99 successes. 1 had a get operation get was corrupt.
ByteArrayProxy.PROXY_BA - 28 runs.  5 successes.  16 segfaults. 7 JVM crashes.  

The ByteBufferProxy's results are similar and need more runs.  I don't know what's going on with PROXY_BA.

**Comment by ChrisTrenkamp** [comment]
I tried turning off NOTLS and kept the write transaction in a dedicated thread and had no affect on either the JVM crashes or the null/corrupt get's.  I'm out of idea's on what to look for.  Any suggestions?

**Comment by benalexau** [comment]
Given the `Verifier` runs successfully for 5 minutes it's hard for me to reproduce and investigate this more fully.

Could you perhaps try your application on another operating system? It would be good to know if this issue only appears on Windows 10. If it happens on other operating system it would suggest this is application logic related, for example something subtle with transactions or writing into buffers that were returned by LMDB etc.

Ideally could you provide a small self-contained sample that I can reproduce the issue with on a local Windows 10 VM?

**Comment by ChrisTrenkamp** [comment]
I don't remember everything I tried, but I think Linux was affected by the random null's.  So, that would probably mean that this problem is OS-agnostic.  I switched to LWJGL's LMDB module and have not had any problems.

**Comment by benalexau** [comment]
Glad you found a way forward. I'll close this ticket as there's unfortunately not much I can do to reproduce this.
