### ISSUE TITLE
issue another release to maven central

### ISSUE THREAD

**Issue by phraktle** [lmdbjava/lmdbjava#13]
Based on my testing so far, current HEAD seems pretty solid. I would suggest releasing a new version so it can be picked up as a dependency.

**Comment by benalexau** [comment]
No worries. will do.

@krisskross you happy with a 0.0.2 release?

More generally I am refactoring the build a bit over the next few days as per issue #14. I will get the build changes made first given an 0.0.2 release offers a full end-to-end (ie to Maven Sync) test.

**Comment by krisskross** [comment]
A 0.0.2 release sounds good!

**Comment by benalexau** [comment]
@phraktle are you happy for 0.0.2 or do you have some more PRs planned for your other tickets (the cursor iterator extensions and byte[] most notably)?

**Comment by phraktle** [comment]
Please go ahead, no plans for further commits for now.

**Comment by benalexau** [comment]
Released 0.0.2. [Travis log here](https://travis-ci.org/lmdbjava/lmdbjava/jobs/148202763). Should be in Maven Central soon.

**Comment by phraktle** [comment]
Thanks, looks good!
