### ISSUE TITLE
Java 11:  Illegal reflective access by org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy

### ISSUE THREAD

**Issue by jubax** [lmdbjava/lmdbjava#130]
I just switched to adoptopenjdk11 (on macOS with lmdbjava 0.6.3) and I now get:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy (file:/.../lmdbjava-0.6.3.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```
Not sure if this has been discussed before. Should I change something in my code or in my environment or is this something which will be fixed?

Thanks!

**Comment by benalexau** [comment]
This is a standard warning that many libraries receive when violating Java encapsulation in Java 9 and beyond. Issue #42 covers the topic in greater detail so I'll close this ticket.
