### ISSUE TITLE
Data corruption bug

### ISSUE THREAD

**Issue by lolepezy** [lmdbjava/lmdbjava#131]
Hi,

We are using lmdbjava in the project that extensively crunches a lot of data and we see that after day or two of working data gets corrupted. It is not very easy to reproduce the problem, it looks pretty random, but we know that the data is corrupted looking at checksums. The bug manifests itself depending on the platform, it seems like it doesn't happen on FreeBSD, but happens on linux and more often on Mac OS X. The issue is pretty hard to isolate, because when we try to stress test separate component, everything seems to be fine. We ruled out hardware problems as well.

Where, do you think, we should be looking to fix the issue? I don't suspect LMDB itself corrupting the data, so the problem is either in our code (I hope for that), or in lmdbjava, or in some JNI machinery.

Is it worth trying different JDKs or try DirectBuffer instead of ByteBuffer? Change some JVM settings? Use valgrind or tool like it? Any hints you could probably give us? Also, if you can have a quick look and, probably, point at some obviously wrong usages of Dbi it would be really nice.

https://github.com/RIPE-NCC/rpki-validator-3/blob/lmdb-storage/rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/lmdb/IxMap.java

Our code is based on this IxMap ('indexed map'), so if something is wrong it has to be wrong in the IxMap. I understand that the issue sounds pretty vague, so if extra clarification would help, I will be happy to provide it.

We are using lmdbjava-0.6.3 with OpenJDK8 on all the mentioned platforms.

Thank you.

**Comment by benalexau** [comment]
I had a look at your code but there's quite a few classes involved and I'm unsure the broader contracts around threading etc. As such I'm not in a good position to comment on whether it's correct. I do see you're using `ByteBuffer` though, which is what I'd recommend at this point given it's the simplest buffer.

It's surprising you're running LmdbJava successfully on FreeBSD, as we don't bundle a native library for FreeBSD. While LmdbJava should happily work with a third party LMDB native library, it makes me wonder which versions of the LMDB system library you're running on the different platforms. Can you clarify?

The easiest way to move forward with this is to run the new `Verifier` class (which was discussed in #124). As 0.6.3 is the latest current release ([Change Log](https://github.com/lmdbjava/lmdbjava/wiki/Change-Log)), I'd suggest copying the `Verifier` [source code](https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/Verifier.java) into your project and running it for an extended period on your test platforms. Please let us know how you go.

**Comment by benalexau** [comment]
I've now released 0.7.0 on Maven Central (see #134) so please try the latest version and its bundled `Verifier`. I'll close this ticket for now; please comment should you like it reopened.
