### ISSUE TITLE
Platform constant error code: ESRCH No such process (3) under JDK8 / Windows 7

### ISSUE THREAD

**Issue by jackmalkovick** [lmdbjava/lmdbjava#132]
I see a lot of configurations that get this error... unfortunately we've got it on our windows machines also... JDK 1.8.0_111-b14 / Windows 7 / 64 bit

Exception in thread "main" org.lmdbjava.LmdbNativeException$ConstantDerviedException: Platform constant error code: ESRCH No such process (3)
	at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:114)
	at org.lmdbjava.Env$Builder.open(Env.java:469)
	at org.lmdbjava.Env$Builder.open(Env.java:486)

**Comment by jackmalkovick** [comment]
Simple test creation code...

	    final Env<ByteBuffer> env = Env.create()
	        .setMapSize(10_485_760)
	        .setMaxDbs(1)
	        .open(new File("c:/temp/lmdb.bin"));

**Comment by benalexau** [comment]
Which version of LmdbJava?

Your `Env` creation code would expect a directory called `C:\temp\lmdb.bin`. Can you try adding [EnvFlags.MDB_NOSUBDIR](https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/EnvFlags.java) to your `open` statement.

If that doesn't fix it, please try cloning the LmdbJava project on your machine then `mvn clean test`.

**Comment by jackmalkovick** [comment]
You were right... That param worked. The error was a little bit strange. Thank you!
