### ISSUE TITLE
Memory leak while using lmdbJava

### ISSUE THREAD

**Issue by lazylad91** [lmdbjava/lmdbjava#139]
Hi
I am reading from lmdb database using lmdbjava library. My process is leaking memory like anything. I am using pool of DirectByteBuffer to send the keys. Lmdb is open only in read only mode.
pmap -x is showing it loads the whole data.mdb file ?
is it true?

**Comment by lazylad91** [comment]
I also noticed that its all resident memory and all pages are claimed to be dirty.

**Comment by benalexau** [comment]
This web page might help explain what's going on: https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/

**Comment by lazylad91** [comment]
@benalexau Thanks for providing the info.

**Comment by benalexau** [comment]
No worries. I'll close this ticket for now. Please feel free to re-open it if you feel LmdbJava is leaking memory as opposed to LMDB operating as designed. Thanks.
