### ISSUE TITLE
Clean stale readers?

### ISSUE THREAD

**Issue by lazylad91** [lmdbjava/lmdbjava#142]
I could not find the implementation of stale_reader_check.
Is there any other way I can do it?

**Comment by benalexau** [comment]
Do you mean `mdb_reader_check` (see [LMDB docs](http://www.lmdb.tech/doc/group__mdb.html))? This is stubbed in the `Library` class but no corresponding method has been added to `Env`. Feel free to submit a PR if you wish (it should be very easy to add).

**Comment by lazylad91** [comment]
I will submit the PR this weekend.
