### ISSUE TITLE
EnvTest crashes

### ISSUE THREAD

**Issue by abstract-thinking** [lmdbjava/lmdbjava#143]
Hi guys,

I'm checkout your code and let it run with **mvn clean package**.

The result is that one test case fails.

[INFO] Running org.lmdbjava.EnvTest
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/mahofmann/playground/java/lmdbjava/target/surefire-reports/2020-01-17T16-38-10_855-jvmRun1.dumpstream

The code is running on an Ubuntu 18.04 machine inside VMware Workstation 15 Player.

Is this behaviour expected?

Thanks,
Markus

**Comment by benalexau** [comment]
Yes. See https://stackoverflow.com/questions/55272870/surefire-maven-plugin-corrupted-stdout-by-directly-writing-to-native-stream-in for background.
