### ISSUE TITLE
Memory usage (stat)

### ISSUE THREAD

**Issue by Chewbizz** [lmdbjava/lmdbjava#144]
From the LMDB documentation, it is not clear to me how I can get the actual disk space used by a .mdb file.

My guess was to call Env.stat() method and Dbi.stat(Txn) method (using a new dedicated read transaction). For each Stat object retrieved this way, I assumed the byte size was :
byteSize = stat.pageSize * (stat.leafPages + stat.branchPages + stat.overflowPages)

But this returns different results from the "du" result using command line.
The "du" command returns the same results as what is reported by /proc/<pid>/smaps file.

For instance, if I take one of my .mdb files which reports 109 MB using "du" (or the "smaps" file), I find 38 MB using my algorithm (sum of all "stat(*)" results).
I assume my algorithm is wrong, but I can't find a way to get the correct disk size (109 MB) using the API.

I know this may be a pure LMDB question, and not related to java binding.
Please let me know if there is another place to ask this question then.
Thank you very much.

**Comment by benalexau** [comment]
This is not supported in the library.

See https://github.com/lmdbjava/benchmarks/blob/18a26ff8ffc00c6435075831ae2fbf3406a46f8e/src/main/java/org/lmdbjava/bench/Common.java#L162 for code I used in the benchmarks to calculate storage use.

**Comment by Chewbizz** [comment]
Thanks a lot for answering quickly. This is what I feared, but I had to ask before introducing a new dependency (to jnr).

**Comment by Chewbizz** [comment]
If I may, I would like to know in the end what I was measuring using Stat objects ?
Is that the current allocated memory (RAM) size ?
Or only a part of the disk size ?
I can create a separate issue if needed. Thank you again.

**Comment by benalexau** [comment]
LMDB generally uses a memory mapped [sparse file](https://en.wikipedia.org/wiki/Sparse_file). 

You need to be careful to not assume the "allocated" size of a sparse file (such as shown by default by `ls`) is the same as the actual "consumed" size. 

`stat` reports the blocks used, which allows you to calculate the actual bytes consumed by the sparse file on disk.

**Comment by Chewbizz** [comment]
Yes, that's why I used the algorithm (based on Stat objects) in my original post to find "the actual bytes consumed by the sparse file on disk".
I expected my algorithm would return the same result as the "reportSpaceUsed" method in your benchmarks, which is the value I can see using the "du" command (which doesn't return the same value as the "ls" command ; see example below). But the values are not the same. And I can't understand where is the difference.

In a given example use-case:
- "ls" command returns 2 GB (as you mention, this is the allocated size, and is out of scope here)
- "du" command returns 109 MB (as would return the "reportSpaceUsed" method)
- computation based on Stat objects returns 38 MB
I expected "du" and Stat computation to both return "the actual bytes consumed by the sparse file on disk". But I get different values. I must be missing something, but I don't catch what. Can you please explain the difference ?

Thank you very much for taking the time to explain to me, I'm truly thankful.

**Comment by Chewbizz** [comment]
If I'm not mistaken, I think I found the answer. I report it back here for others: it is described here https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/
I already read this page before but didn't take into account that extra disk space consumed for MVCC was not cleared up from disk.
This means "du" (and reportSpaceUsed) report both actual database size plus previous transactions/isolations of data that has not been re-written yet.
Whereas Stat objects return the actual "used" database size (by data or by active transactions/isolations).
I have no complete guarantee that my algorithm is correct though. I hope it is.
