### ISSUE TITLE
Txn allocation overhead?

### ISSUE THREAD

**Issue by phraktle** [lmdbjava/lmdbjava#15]
While doing some performance testing for a simple put operation, I'm getting somewhat (~15%) worse performance than with `lmdbjni`. Based on profiling, it seems to me that this is related to buffer allocations the `Txn` constructor. Could the allocations for the key and value buffers be avoided there? The key and value buffers that are to be written are already allocated off-heap in this use-case, so this seems unnecessary.

**Comment by phraktle** [comment]
Actually, the problem is that `BufferProxy#deallocate` is not called the key/value buffers in `Txn` when the transaction is committed, so they are not actually recycled, just GC'd.

**Comment by phraktle** [comment]
The usage of the `committed` flag in `Txn` is a bit confusing too, since `abort` also sets it to `true`. Calling `reset` doesn't seem to reset it though. Suggest reviewing this code and adding some test case ensuring proper state management and deallocation.

**Comment by benalexau** [comment]
@phraktle does PR #16 resolve this? How did the performance look after the state machine and `Txn` recycling?

**Comment by phraktle** [comment]
Performance looks good now (better than with lmdbjni).
