### ISSUE TITLE
allow configuration of target directory for extracted library

### ISSUE THREAD

**Issue by rpdai** [lmdbjava/lmdbjava#155]
lmdbjava is hard-coded to extract to the temp directory.

However, many system policies require the temporary directory to be noexec. This will prevent the binary library code from being executed.

On such systems, configuring an alternative location for the shared library would be very useful.

**Comment by benalexau** [comment]
Thanks for reporting this.

As per the commit, you can now specify a `lmdbjava.extract.dir` system property to control which directory is used for the extraction.

**Comment by rpdai** [comment]
Awesome! Thanks for such a rapid turnaround!

I've raised a matching issue in JFFI. While that's open, it'll be necessary to install the jnr jffi stub onto the library path, but having this option in lmdbjava definitely saves some steps.
