### ISSUE TITLE
NoSuchMethodError: java.nio.ByteBuffer.clear()

### ISSUE THREAD

**Issue by miner** [lmdbjava/lmdbjava#158]
This is the same problem as issue #116 but with the latest lmdbjava 0.8.0.  (I have JDK 8 on my machine.)  I adapted my code for the CursorIterator design changes #154, but my project still failed with the NoSuchMethodError due to the (old) Java API changes in ByteBuffer between JDK 8 and 9.  As discussed last time, JDK 8 is close to end of life.  I updated to a JDK 11 and everything is working again for me.  I suggest that you document the minimum required Java version.

**Comment by benalexau** [comment]
Thanks for the bug report. 

The underlying cause of this was the CI transition last month from Travis and AppVeyor to GitHub Actions. In commit 2f8527b I have changed the deployment step to use Java 8 and added a comment to the workflow file to ensure it isn't accidentally increased in the future.

Can you please try out 0.8.1-SNAPSHOT and confirm if it works OK for you? If so I will perform a release.

Regarding your suggestion of documenting the minimum required Java version, the home page notes we test on Java 8, 11 and 14, so it should work on any of those versions. We'll keep targeting Java 8 for now given there are so many vendors offering long-term support of that specific Java version.

**Comment by miner** [comment]
I tested with 0.8.1-SNAPSHOT.  It works for me with both Java 8 and 11.   I thought for a moment that you were dropping Java 8 support, but I'm happy to see that you want to keep it.  Thanks.

**Comment by benalexau** [comment]
Thanks for testing the snapshot and confirming it worked.

I have released 0.8.1, which is now available at Maven Central: https://repo1.maven.org/maven2/org/lmdbjava/lmdbjava/0.8.1/
