### ISSUE TITLE
Handling of "lmdbjava-native-library-<number>.dll" files

### ISSUE THREAD

**Issue by jubax** [lmdbjava/lmdbjava#166]
Hi,

when running lmdbjava in Tomcat (under Windows) then on startup the LMDB DLL is copied to the temporary folder of Tomcat.

As far as I see this stems from Library.java 

```
file = createTempFile("lmdbjava-native-library-", suffix, dir);
file.deleteOnExit();
```
The problem is now that the DLL is only deleted when we have a clean shutdown. So over time the temporary folder of Tomcat fills up with multiple copies of the LMDB DLL.

I wonder if something could be done to avoid this. E.g. by always using the same name (instead of a generated suffix)?

Thanks,

Jürgen

**Comment by benalexau** [comment]
The LMDB native library extraction process occurs in a `static` initializer. In the typical case LmdbJava is used in applications which have their own JVM and a single classloader. Under Tomcat you're likely experiencing additional DLLs owing to the multiplicity of classloaders.

My suggestion would be to set the `lmdbjava.native.lib` system property to a location where you have manually provided the LMDB DLL.
