### ISSUE TITLE
Is there plan to support encryption at rest for db file?

### ISSUE THREAD

**Issue by chenqi0805** [lmdbjava/lmdbjava#171]
If yes, what will be the encryption standards? Not sure if it is just an issue of java binding or LMDB itself.

**Comment by benalexau** [comment]
Neither LMDB nor LmdbJava provide any form of encryption. 

You really have 3 main options when using LMDB and require encryption (assuming you're on Linux):

1. Encrypt the values using Java before you store them. You should not encrypt the keys as that would defeat the main benefit of using an ordered key-value store in the first place.

2. Encrypt an entire partition and put the LMDB files on that partition.

3. Create an encrypted file system container, mount it to a convenient file system location, and put the LMDB files inside that file system location.

I use option 2 on my Kubernetes worker nodes with a "network bound disk encryption" setup based on Tang and Clevis.

I use option 3 on my Tang server to protect the Tang keys themselves. Here's a quick copy and paste that shows how to create a directory that is encrypted:

```bash
# Set up an encrypted file container
dd if=/dev/urandom of=/root/tang.img bs=1M count=100 iflag=fullblock
cryptsetup luksFormat /root/tang.img
cryptsetup open /root/tang.img tang
mkfs.ext4 /dev/mapper/tang
```

Here's how to mount it:

```bash
# Open encrypted file container
cryptsetup open /root/tang.img tang

# Mount encrypted file container
mount /dev/mapper/tang /var/db/tang
```

Of course nothing is going to protect the data if the file system is already unlocked or mounted.

**Comment by chenqi0805** [comment]
@benalexau Thanks a lot for sharing!
