### ISSUE TITLE
Why does calling db.delete not free database storage

### ISSUE THREAD

**Issue by kevinLuan** [lmdbjava/lmdbjava#173]
Execute the following example

final Dbi<ByteBuffer> db = env.openDbi(DB_1, MDB_CREATE, MDB_DUPSORT);
 for (int i = 0; i < 1000; i++) {
      try (Txn<ByteBuffer> txn = env.txnWrite();) {
        db.delete(txn, $key, $value);
      }
  }
After all the added data keys are deleted, the database file remains unchanged

$  ls -lsh
total 196864
196736 -rw-r--r--  1 kevin  staff    88M  2 27 15:30 myDataBase
   128 -rw-r--r--  1 kevin  staff    63K  2 27 15:16 myDataBase-lock

In addition, I found a particularly interesting phenomenon, if I write a single thread of continuous 1 million data, the database storage file size is 88M, if I write, while start multi-thread read, the database file will appear skyshot to dozens of GB files, why is this? May I ask how to solve it?

**Comment by benalexau** [comment]
If you have a look at https://github.com/lmdbjava/lmdbjava/wiki/Storage-Efficiency it discusses the relationship between transactions and the differing sizes you will see reported using `ls`, `du` and `stat`. There are some storage space efficiency suggestions on that page which you might find helpful.
