### ISSUE TITLE
Uplift jnr-ffi to v2.2.2 for java 15 support

### ISSUE THREAD

**Issue by at055612** [lmdbjava/lmdbjava#174]
jnr-ffi pulls in asm (currently v7.1) which only supports up to Java 13.  asm 9.1 (as used by jnr-ffi v2.2.2) supports up to java 17.

**Comment by at055612** [comment]
If you are happy to merge this PR, please can you release a new version of lmdbjava?

**Comment by benalexau** [comment]
Thanks @at055612.

Regarding making a new release, for the last 20 years I've maintained a "Zero Bug Policy" which means I don't make any release if there are any known bugs. As such issue #164 is currently blocking the release and I haven't had the chance to explore it just yet. You are most welcome to take a look if you have some spare cycles, or alternately you could also use a snapshot release in the interim.
