### ISSUE TITLE
Platform constant error code: EBUSY Resource busy

### ISSUE THREAD

**Issue by punk8** [lmdbjava/lmdbjava#176]
I have encountered the problem shown in the title and would like to ask what the main cause is
![image](https://user-images.githubusercontent.com/26299922/123044263-0441c200-d42c-11eb-827a-6f235c57b8fa.png)

**Comment by benalexau** [comment]
Is this still an issue? Is the database on a standard (non-networked, read-write) file system? Has another process opened it exclusively?  Which operating system are you using?

**Comment by punk8** [comment]
Already solved
