### ISSUE TITLE
Please can you suggest me any document or website or any study material for LMDB Database Study.

### ISSUE THREAD

**Issue by UditKodgir** [lmdbjava/lmdbjava#177]
Hi, I’m @UditKodgir
I’m interested in learning LMDB database...
Please can you suggest me any document or website or any study material for LMDB Database Study.

**Comment by benalexau** [comment]
LmdbJava is a wrapper over LMDB.

Assuming you are a Java developer start with the [documentation section](https://github.com/lmdbjava/lmdbjava#documentation) of the home page. If you are after more general LMDB information try the [LMDB home page](https://symas.com/lmdb/).
