### ISSUE TITLE
Portability?

### ISSUE THREAD

**Issue by buko** [lmdbjava/lmdbjava#179]
The documentation doesn't quite detail LMDB's portability story. My understanding is that LMDB is portable across all major platforms (linux, windows, and macos). Is it portable to non-Intel chipsets? ARM? AWS Graviton?

Also it's not clear if apps built on lmdbjava are portable. My understanding is that when you declare a Maven dependency on lmdbjava it pulls in just the native libs needed to support the build platform. The resulting distribution (build output) includes just the native libs for whatever platform built it but not other platforms. So, in practice, different distributions would need to built for each support platform (though there would be essentially zero code changes between the builds). Is this correct?

BTW Maybe this could be added to a 'Portability' page on the wiki.

**Comment by benalexau** [comment]
There is some basic early-stage ARM support in the LmdbJava Native project but we do not bundle these inside the LmdbJava JAR.

The LmdbJava JAR always contains x86_64 builds of the LMDB native library for Linux, Windows and MacOS. It does not include any others. If you need another platform you need to install LMDB natively on that platform using and then use the system properties defined in the [Library](https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/Library.java) class to control its use.

**Comment by benalexau** [comment]
I believe the question was answered in my September 2021 reply so I will close this ticket.
