### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Unknown result code 131

### ISSUE THREAD

**Issue by kk00ss** [lmdbjava/lmdbjava#18]
Code is based on snippet from another issue
```
import java.io.File;
import java.nio.ByteBuffer;
import java.util.concurrent.ThreadLocalRandom;

import org.lmdbjava.Dbi;
import org.lmdbjava.DbiFlags;
import org.lmdbjava.Env;

public class Test {

    public static void main(String[] args) {
        File path = new File("lmdbTest");
        path.mkdir();
        for (; ; ) {
            writeFull(path);
        }
    }

    private static void writeFull(File path) {
        int size = 1;
        int MB = 1024 * 1024 ;//* 1024;
        Env<ByteBuffer> env = Env.create().setMapSize(size * MB).setMaxDbs(1).open(path);
        Dbi<ByteBuffer> db = env.openDbi("test", DbiFlags.MDB_CREATE);

        byte[] k = new byte[64];
        ByteBuffer key = ByteBuffer.allocateDirect(64);
        ByteBuffer val = ByteBuffer.allocateDirect(MB/4);

        ThreadLocalRandom rnd = ThreadLocalRandom.current();
        int count = 0;
        for (int i = 0; i < 1024*100; i++) {
            try {
                rnd.nextBytes(k);
                key.clear();
                key.put(k).flip();
                val.clear();
                db.put(key, val);
                System.out.println("written " + ++count);
            } catch (Exception e) {
                //e.printStackTrace(System.out);
                System.out.println("map full, old size = "+size+" MB");
                db.close();
                env.close();
                size++;
                env = Env.create().setMapSize(size * MB).setMaxDbs(1).open(path);
                db = env.openDbi("test", DbiFlags.MDB_CREATE);
            }
        }

        System.out.println("closing db");
        db.close();

        System.out.println("closing env");
        env.close();
    }

}```
Exception itself
```Exception in thread "main" java.lang.IllegalArgumentException: Unknown result code 131
	at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:96)
	at org.lmdbjava.Env$Builder.open(Env.java:376)
	at org.lmdbjava.Env$Builder.open(Env.java:388)
	at rhinodog.Run.Test.writeFull(Test.java:48)
	at rhinodog.Run.Test.main(Test.java:18)```

**Comment by kk00ss** [comment]
Could it be due to the usage of 32bit built of LMDB ? This happens on windows 10, I'll get my hands on Linux env soon to test it.

**Comment by benalexau** [comment]
LmdbJava only supports 64-bit platforms. There are a few reasons for this:

1. The main use case for LmdbJava is storing large volumes of data. 32-bit is limited to roughly 3 GB. If an application has more modest data storage requirements, chances are it could use a different Java persistence API and achieve performance and safety benefits by staying completely within the Java heap and using pure Java code (side-stepping the `Unsafe` / direct / JNI-related calls).
2. LmdbJava has many locations where memory addresses are copied between Java and C. We've used `long` as it's 64-bit and this simplifies efficient interop via JNR-FFF and `Unsafe`. If we supported 32-bit we'd require conditional logic to handle the C-side `void *` being 32-bits and our statically-determined `struct` offsets no longer being accurate. We'd also need to conditionally handle address read/writes, as we couldn't read/write a `long` to an offset containing a 32-bit memory address.

I can see some use cases for 64-bit support (eg small developer machines using a 32-bit OS for R&D and then deploying to a 64-bit server) but I'm unsure if it's worth the extra complexity in LmdbJava.

Assuming others agree with the above, what I'd suggest is `Library`'s static initializer be modified to raise a 32-bit architecture exception message. While the 32-bit requirement is mentioned in the `TutorialTest` we encourage people to read to learn about LmdbJava, it's very easy to miss and a more descriptive exception would save users a lot of time and effort checking their code etc.

**Comment by kk00ss** [comment]
I'm running 64 bit OS, it's just 2GB file size where the problem manifests
itself
8 Авг 2016 г. 3:29 пользователь "Ben Alex" <notifications@github.com>
написал:

**Comment by kk00ss** [comment]
Same exception is thrown when I'm trying to allocate 10GB Environment on windows, with same code snippet. @benalexau  - it would be cool if you tried to reproduce the issue with my code snippet,

**Comment by kk00ss** [comment]
I've installed linux to test same code, results are very strange, on the system with 16GB RAM and 50+ GB SSD (there is a lot of space still) 
```
map full, old size = 1 GB
Exception in thread "main" org.lmdbjava.LmdbNativeException$ConstantDerviedException: Platform constant error code: ENOMEM (12)
	at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:98)
	at org.lmdbjava.Env$Builder.open(Env.java:376)
	at org.lmdbjava.Env$Builder.open(Env.java:388)
	at rhinodog.Run.Test.writeFull(Test.java:79)
	at rhinodog.Run.Test.main(Test.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)```

**Comment by benalexau** [comment]
On my tests this appears to be connected with the creation of the 2,048 `Env`:

```
package au.com.acegi.core.fff;

import java.io.File;
import java.nio.ByteBuffer;
import org.junit.Test;
import org.lmdbjava.Env;
import static org.lmdbjava.EnvFlags.MDB_NOSUBDIR;

public final class Issue18 {

  @Test
  public void test() {
    final File path = new File("lmdbTest");
    path.deleteOnExit();
    final int MB = 1024 * 1024;
    for (int i = 1; i < 2049; i++) {
      try (Env<ByteBuffer> env = Env.create().setMapSize(i * MB).setMaxDbs(1)
          .open(path, MDB_NOSUBDIR)) {
        System.out.println(i + " " + env.info().lastPageNumber);
      }
    }
  }
}
```

Gives:

```
.....
2046 1
2047 1
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.875 sec <<< FAILURE! - in au.com.acegi.core.fff.Issue18
test(au.com.acegi.core.fff.Issue18)  Time elapsed: 0.822 sec  <<< ERROR!
org.lmdbjava.LmdbNativeException$ConstantDerviedException: Platform constant error code: ENOMEM (12)
	at au.com.acegi.core.fff.Issue18.test(Issue18.java:18)


Results :

Tests in error: 
  Issue18.test:18 » ConstantDervied Platform constant error code: ENOMEM (12)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

I suspect this is being caused by the creation of so many `Env`s in a single process and we are hitting an internal LMDB limit of some type, but we would need to reach out to Howard Chu to confirm (I did a quick `grep` of LMDB source code but didn't find an obvious 2,048 value, but returning `ENOMEM` is a common return code from LMDB). Have you tried something simpler, like running the provided [tutorial](https://github.com/lmdbjava/lmdbjava/tree/master/src/test/java/org/lmdbjava/TutorialTest.java) on this machine?

**Comment by kk00ss** [comment]
First - environment is closed before new one is created, if the driver works correctly there should be no more than 1 open Environment at any given moment. 
Second - I'm pretty sure that hard limit in LMDB is 64 for the number of open Environments. 
Third - If you change MB to GB (and the corresponding number of course) than you will see such an output : 
```written 1
written 2
written 3
map full, old size = 1 GB
Exception in thread "main" java.lang.IllegalArgumentException: Unknown result code 131
	at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:96)
	at org.lmdbjava.Env$Builder.open(Env.java:376)
	at org.lmdbjava.Env$Builder.open(Env.java:388)
	at rhinodog.Run.Test.writeFull(Test.java:78)
	at rhinodog.Run.Test.main(Test.java:21)
``` 
Which looks like the problem is with the MMap size. 
I've tested same code on Fedora Linux and got same result. 
I've heard reports from people using LMDB in prod, I've tested RocksDB JNI and everything was fine.

**Comment by krisskross** [comment]
Might be that `ENOMEM` originates from LMDB since [mdb_env_create](https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/mdb.c#L4137) returns this code if the `calloc` call fails.

**Comment by benalexau** [comment]
Found the issue:

```
  @Test
  public void overflow() {
    final int MB = 1024 * 1024;
    final int i2047 = 2047;
    final int i2048 = 2048;
    final int x2047 = MB * i2047;
    final int x2048 = MB * i2048;
    System.out.println(x2047);
    System.out.println(x2048);
  }
```

Gives:

```
2146435072
-2147483648
```

As such `1024 * 1024 * 2048` overflows the integer being passed to `Builder.setMapSize(long)`. On Linux that manifests itself as an `ENOMEM`. On Windows it manifests itself as error code 131, which [MSDN Windows System Error Codes (0-499)](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx) defines as:

> ERROR_NEGATIVE_SEEK
>    131 (0x83)
>   An attempt was made to move the file pointer before the beginning of the file.

The fix is nice and simple. In my earlier test, add a cast:

```
      try (Env<ByteBuffer> env = Env.create().setMapSize(i * MB).setMaxDbs(1)       // before
      try (Env<ByteBuffer> env = Env.create().setMapSize((long)i * MB).setMaxDbs(1) // after
```

On my machine I was able to use the above test to create and close 200,000 `Env`s without error.

To avoid new users encountering this in the future, I have also added a check to `Builder.setMapSize(long)` so an `IllegalAgumentException` is raised if a negative value is given. There is a corresponding test to prove it works. I did not add similar checks for the other `Builder` methods as I don't consider them likely to be calculated and subject to overflow risk, whereas a map size calculation is more likely.

Would you please try the above cast and confirm it fixes your issue?

**Comment by benalexau** [comment]
Also from today we now automatically publish snapshots in the [OSS Sonatype Snapshots Repo](https://oss.sonatype.org/content/repositories/snapshots/org/lmdbjava/lmdbjava) so if you like you might want to test against version 0.0.3-SNAPSHOT. This should return the new exception if a negative map size is specified.

**Comment by kk00ss** [comment]
Well I'm ashamed of that error, but fixing it doesn't yield any progress
```long size = 1;
        long GB = 1024 * 1024 * 1024;
        Env<ByteBuffer> env = Env.create().setMapSize(GB).setMaxDbs(1).open(path);
        Dbi<ByteBuffer> db = env.openDbi("test", DbiFlags.MDB_CREATE);

        byte[] k = new byte[64];
        ByteBuffer key = ByteBuffer.allocateDirect(64);
        ByteBuffer val = ByteBuffer.allocateDirect((int)GB/4);

        ThreadLocalRandom rnd = ThreadLocalRandom.current();
        int count = 0;
        for (int i = 0; i < 100; i++) {
            try {
                rnd.nextBytes(k);
                key.clear();
                key.put(k).flip();
                val.clear();
                db.put(key, val);
                System.out.println("written " + ++count);
            } catch (Exception e) {
                //e.printStackTrace(System.out);
                System.out.println("map full, old size = "+size+" GB");
                db.close();
                env.close();
                size++;
                long newSize = size * GB;
                System.out.println("new mapSize = "+newSize);
                env = Env.create().setMapSize(newSize).setMaxDbs(1).open(path);
                db = env.openDbi("test", DbiFlags.MDB_CREATE);
            }
        }

        System.out.println("closing db");
        db.close();

        System.out.println("closing env");
        env.close();
```
This code still throws the same exception on attempt to resize environment

**Comment by kk00ss** [comment]
Here is smaller snippet that reproduces same issue:
```
long size = 10;
        long GB = 1024 * 1024 * 1024;
        long newSize = size * GB;
        System.out.println("newSize = "+newSize);
        Env<ByteBuffer> env = Env.create().setMapSize(newSize).setMaxDbs(1).open(path);
```

**Comment by benalexau** [comment]
I put your code fragment into a test case as follows:

```
package org.lmdbjava;

import java.io.File;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.concurrent.ThreadLocalRandom;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

public class QuickTest {

  @Rule
  public final TemporaryFolder tmp = new TemporaryFolder();
  
  @Test
  public void test() throws IOException {
    long size = 1;
    long GB = 1024 * 1024 * 1024;
    File path = tmp.newFolder();
    Env<ByteBuffer> env = Env.create().setMapSize(GB).setMaxDbs(1).open(path);
    Dbi<ByteBuffer> db = env.openDbi("test", DbiFlags.MDB_CREATE);

    byte[] k = new byte[64];
    ByteBuffer key = ByteBuffer.allocateDirect(64);
    ByteBuffer val = ByteBuffer.allocateDirect((int) GB / 4);

    ThreadLocalRandom rnd = ThreadLocalRandom.current();
    int count = 0;
    for (int i = 0; i < 100; i++) {
      try {
        rnd.nextBytes(k);
        key.clear();
        key.put(k).flip();
        val.clear();
        db.put(key, val);
        System.out.println("written " + ++count);
      } catch (Exception e) {
        //e.printStackTrace(System.out);
        System.out.println("map full, old size = " + size + " GB");
        db.close();
        env.close();
        size++;
        long newSize = size * GB;
        System.out.println("new mapSize = " + newSize);
        env = Env.create().setMapSize(newSize).setMaxDbs(1).open(path);
        db = env.openDbi("test", DbiFlags.MDB_CREATE);
      }
    }

    System.out.println("closing db");
    db.close();

    System.out.println("closing env");
    env.close();

  }

}
```

Then with `mvn clean test` I receive:

```
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.lmdbjava.CursorIteratorTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.475 sec - in org.lmdbjava.CursorIteratorTest
Running org.lmdbjava.ResultCodeMapperTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.lmdbjava.ResultCodeMapperTest
Running org.lmdbjava.MetaTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.lmdbjava.MetaTest
Running org.lmdbjava.LibraryTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.lmdbjava.LibraryTest
Running org.lmdbjava.EnvTest
Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.314 sec - in org.lmdbjava.EnvTest
Running org.lmdbjava.QuickTest
written 1
written 2
written 3
map full, old size = 1 GB
new mapSize = 2147483648
written 4
written 5
written 6
written 7
map full, old size = 2 GB
new mapSize = 3221225472
written 8
written 9
written 10
written 11
map full, old size = 3 GB
new mapSize = 4294967296
written 12
written 13
written 14
written 15
map full, old size = 4 GB
new mapSize = 5368709120
written 16
written 17
written 18
written 19
map full, old size = 5 GB
new mapSize = 6442450944
written 20
written 21
written 22
written 23
map full, old size = 6 GB
new mapSize = 7516192768
written 24
written 25
written 26
written 27
map full, old size = 7 GB
new mapSize = 8589934592
written 28
written 29
written 30
written 31
map full, old size = 8 GB
new mapSize = 9663676416
written 32
written 33
written 34
written 35
map full, old size = 9 GB
new mapSize = 10737418240
written 36
written 37
written 38
written 39
map full, old size = 10 GB
new mapSize = 11811160064
written 40
written 41
written 42
written 43
map full, old size = 11 GB
new mapSize = 12884901888
written 44
written 45
written 46
written 47
map full, old size = 12 GB
new mapSize = 13958643712
written 48
written 49
written 50
written 51
map full, old size = 13 GB
new mapSize = 15032385536
written 52
written 53
written 54
written 55
map full, old size = 14 GB
new mapSize = 16106127360
written 56
written 57
written 58
written 59
map full, old size = 15 GB
new mapSize = 17179869184
written 60
written 61
written 62
written 63
map full, old size = 16 GB
new mapSize = 18253611008
written 64
written 65
written 66
written 67
map full, old size = 17 GB
new mapSize = 19327352832
written 68
written 69
written 70
written 71
map full, old size = 18 GB
new mapSize = 20401094656
written 72
written 73
written 74
written 75
map full, old size = 19 GB
new mapSize = 21474836480
written 76
written 77
written 78
written 79
map full, old size = 20 GB
new mapSize = 22548578304
written 80
closing db
closing env
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.002 sec - in org.lmdbjava.QuickTest
Running org.lmdbjava.TxnTest
Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.036 sec - in org.lmdbjava.TxnTest
Running org.lmdbjava.CursorTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.18 sec - in org.lmdbjava.CursorTest
Running org.lmdbjava.ByteBufferProxyTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in org.lmdbjava.ByteBufferProxyTest
Running org.lmdbjava.MaskedFlagTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in org.lmdbjava.MaskedFlagTest
Running org.lmdbjava.TutorialTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec - in org.lmdbjava.TutorialTest
Running org.lmdbjava.DbiTest
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.718 sec - in org.lmdbjava.DbiTest

Results :

Tests run: 103, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.420 s
[INFO] Finished at: 2016-08-11T10:35:16+10:00
[INFO] Final Memory: 30M/432M
```

It's possible this was corrected as part of commit d83d542627c0fb64d8f378cd522cad84d943fc84. Would you like to give it another try with a snapshot release? If you still encounter difficulties, would you mind please providing a complete executable test case which reproduces it on your machine for me to try out?

**Comment by kk00ss** [comment]
That doesn't work with 0.0.2.
How do I load snapshot with Maven ?

2016-08-11 3:38 GMT+03:00 Ben Alex <notifications@github.com>:

**Comment by benalexau** [comment]
@kk00ss just change your LMDB version to 0.0.3-SNAPSHOT and either add an extra repository to your project POM or add a profile to your Maven-wide settings as [explained here](http://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository). If your organisation has a repository manager like Nexus they can also add the snapshot repository that way.

**Comment by kk00ss** [comment]
Well, your code snippet doesn't work for me on Windows, and I don't have
installed linux at the moment. It looks weird to me...

2016-08-11 16:34 GMT+03:00 Ben Alex <notifications@github.com>:

**Comment by benalexau** [comment]
I'm unclear from your last comment whether you tried my code snippet with 0.0.3-SNAPSHOT or 0.0.2?

I use Linux, but the CI environment includes Linux, OS X and Windows. All of these are successfully running all tests, including the new `EnvTest.mapFull()` as per commit d83d542.

As there have been several bug fixes in the fortnight since we released 0.0.2 and it might assist you in trying out 0.0.3 as part of this ticket, I have now [released 0.0.3](http://search.maven.org/#artifactdetails%7Corg.lmdbjava%7Clmdbjava%7C0.0.3%7Cjar) via [Travis](https://travis-ci.org/lmdbjava/lmdbjava/jobs/151700747). Would you please try out your code with the Maven Central-hosted 0.0.3 release and let me know how you go?

**Comment by kk00ss** [comment]
I've tested it on 0.0.2 and 0.0.3-SNAPSHOT and 0.0.3 just now - fails for all of them
```
written 1
written 2
written 3
map full, old size = 1 GB
new mapSize = 2147483648

java.lang.IllegalArgumentException: Unknown result code 131

	at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:96)
	at org.lmdbjava.Env$Builder.open(Env.java:377)
	at org.lmdbjava.Env$Builder.open(Env.java:393)
	at lmdbjavaTest.test(lmdbjavaTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by benalexau** [comment]
Can you please let me know the Windows version you're using (product name, version, 64-bit)? I'll see if I can find a VM to run the tests at my end.

**Comment by kk00ss** [comment]
Windows 10 Home 64-bit.

2016-08-12 14:15 GMT+03:00 Ben Alex <notifications@github.com>:

**Comment by benalexau** [comment]
I was able to reproduce your issue using a 64-bit Windows Vista VM with 16 GB RAM and the `QuickTest` provided in my [earlier comment](https://github.com/lmdbjava/lmdbjava/issues/18#issuecomment-239046368).

After reproducing it, I started to edit the code and noticed if I subtract 1 from the `newSize` the problem went away, at least for one iteration.

That got me wondering if perhaps something is wrong with LmdbJava 0.0.3's bundled
`org/lmdbjava/lmdbjava-native-windows-x86_64.dll`. By way of background, the DLL is compiled as part of the [LmdbJava Native](https://github.com/lmdbjava/native)'s Travis build. It is achieved via cross-compilation on Travis Linux VM and uses `x86_64-w64-wingw32-gcc` as shown in the relevant [release log line](https://travis-ci.org/lmdbjava/native/jobs/147700174#L2326). Quoting the [cross compilation documentation](https://sourceforge.net/p/mingw-w64/wiki2/CrossQuickstart/):

> x86_64-w64-mingw32 for binaries built to run on 64-bit Windows platforms

As such, it looked OK to me. Just to make sure, I used the `petype` Perl script from [this Stackoverflow answer](http://stackoverflow.com/a/495305/245018) to validate the bundled DLL is indeed 64-bit:

```
$ petype ./org/lmdbjava/lmdbjava-native-windows-x86_64.dll
AMD64
```

My next step was to install a 64-bit LMDB DLL from a third party and run the test with `-Dlmdbjava.disable.extract=true` (thus disabling the LmdbJava-bundled DLL), but I was unable to find a source I'd trust enough to install a DLL on my VM. While NuGet has [an LMDB package](https://www.nuget.org/packages/lmdb-v120-clean/), my old Vista VM is incapable of running NuGet without an upgrade of so many dependencies it's infeasible.

With that path blocked, I fetched a fresh cup of tea and thought maybe we're seeing something strange with the multiplication, even though I could see the computed sizes were logically correct. Regardless, I used [ByteUnits](https://github.com/JakeWharton/byteunits) and surprisingly found no problem with 2 - 6 GB map sizes. However that was with `DecimalByteUnit.GIGABYTES`. When I switched to `BinaryByteUnit.GIBIBYTES`, the problem came back.

I then realised the fault was specific to certain bits being high in the `long` map size. Upon further investigation I found LmdbJava's `Lmdb.mdb_env_mapsize(@In Pointer env, long size)` was declaring a `long`, whereas the C side wanted a `size_t`. I added `@size_t` in front of `long size` and the problem was solved (commit 66a26321fbaa848625c3bb39e91239e056e04289)!

Congratulations on the strangest bug report so far for LmdbJava! I provided the above background to show how I stumbled across it and offer some verification information should others similarly wish to verify the cross-compilation approach.

If you could please test your code against 0.0.4-SNAPSHOT on your machine I would be appreciative. Thanks for your patience working through this issue.

**Comment by kk00ss** [comment]
Finally it works, thank you very much for the effort. 
About strange bugs - with different LMDB java driver I have an issue with large write transactions,
in short when reaching 4GB MapSize limit, write transaction is aborted because of MapFull error and after I reopen environment with larger MapSize it says environment is not proper LMDB file. But it's actually even worse - after restart file is not recognized as LMDB database at all.  
I'll port my code to lmdbjava and test it again, but there are chances to see even stranger bug.

**Comment by benalexau** [comment]
@kk00ss glad it's working for you now. It would be great if you can test LmdbJava 0.0.4-SNAPSHOT with larger workloads on Windows and let us know how you go. It doesn't take long to fill 4GB, even if use small value sizes. I've written more about [LMDB page sizes here](https://github.com/lmdbjava/benchmarks/blob/master/results/20160710/README.md#test-2-determine-24816-kb-byte-values) if this is of interest.

**Comment by kk00ss** [comment]
I've tested it with 12GB so far.
14 Авг 2016 г. 1:33 пользователь "Ben Alex" <notifications@github.com>
написал:

**Comment by kk00ss** [comment]
I think that header size for overflow page in LMDB is 16 bytes, and not 12.
https://mobile.twitter.com/hyc_symas/status/676146127784296448
I don't know if you will be able to see, but Howard told me that.

**Comment by benalexau** [comment]
Just quoting part of an email from Howard to @krisskross and I:

> Also, recall that with larger values, there is no 16 byte header on subsequent overflow pages. So jumping up from your 4084 byte record, you can add increments of 4096 bytes and each of those will also be optimally packed. So your next record size from 4084 should be 8180 bytes.

As such it doesn't apply to subsequent overflow pages for the same record. You can keep adding 4096 bytes without subtracting the header.
