### ISSUE TITLE
Automatic Module Name

### ISSUE THREAD

**Issue by buko** [lmdbjava/lmdbjava#180]
lmdbjava should use an Automatic Module Name as described in [Automatic-Module-Name: Calling all Java Library Maintainers](http://branchandbound.net/blog/java/2017/12/automatic-module-name/). This would mostly involve adding a single line to the lmdbjava manifest:

```
Automatic-Module-Name: org.lmdbjava.engine
```

The word 'engine' here is used to identify the main database engine jar (lmdbjava.jar) from other potential jars like tools or tests that may be introduced in the future.

Once an Automatic-Module-Name is added it will smooth out Java 9+ builds.

**Comment by benalexau** [comment]
There's a wider conversation about Java 9+ support in #42. I'll close this current ticket as it's easier to keep the context of the conversation in a single place.
