### ISSUE TITLE
Documentation Bug: Directory must exist before Env.open is called

### ISSUE THREAD

**Issue by buko** [lmdbjava/lmdbjava#181]
On Windows if you pass Env.open() a File to a directory that doesn't exist then you will get a very strange error:

```
 org.lmdbjava.LmdbNativeException$ConstantDerivedException: Platform constant
		 error code: ESRCH No such process (3) at
		 org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:114) at
		 org.lmdbjava.Env$Builder.open(Env.java:495) at
		 org.lmdbjava.Env$Builder.open(Env.java:512)
```

There's two issues here: (1) the error is not very helpful and doesn't help a developer actually fix the issue and (2) the requirement that the directory must exist before Env.Builder.open is called  isn't documented in javadoc.

**Comment by benalexau** [comment]
Most people use `EnvFlags.MDB_NOSUBDIR` and provide a filename for their database environment.

We cannot really improve this error message as it's coming from the LMDB native library side and we just convert it in `ResultCodeMapper`.

Having said that, I would be happy to apply a PR that does a defensive Java-side check in `Env.open(..)` before attempting to call out to LMDB. That way we could return a more meaningful exception to the user regardless of the flags they used. If this is of interest please feel free to submit a PR.

**Comment by benalexau** [comment]
Closing this ticket as it's better addressed via a PR.
