### ISSUE TITLE
There is very large disk io when I use iterator..

### ISSUE THREAD

**Issue by alexBaiJW** [lmdbjava/lmdbjava#184]
`
"traversal-thread-12" #22 daemon prio=5 os_prio=0 tid=0x00007f40c0390000 nid=0x99cd runnable [0x00007f409eeed000]
   java.lang.Thread.State: RUNNABLE
        at org.lmdbjava.Library$Lmdb$jnr$ffi$0.mdb_cursor_get$jni$15(Native Method)
        at org.lmdbjava.Library$Lmdb$jnr$ffi$0.mdb_cursor_get(Unknown Source)
        at org.lmdbjava.Cursor.get(Cursor.java:176)
        at org.lmdbjava.CursorIterable.executeCursorOp(CursorIterable.java:137)
        at org.lmdbjava.CursorIterable.update(CursorIterable.java:172)
        at org.lmdbjava.CursorIterable.access$100(CursorIterable.java:52)
        at org.lmdbjava.CursorIterable$1.hasNext(CursorIterable.java:99)
`

![Uploading image.png…]()

`
Iterator<CursorIterable.KeyVal<ByteBuffer>> iterator = db.iterate(readerTxn, KeyRange.closedOpen(start, end)).iterator();
while (iterator.hasNext()) {
                            current = iterator.next().val();
                            for (int i = 0; i < current.limit(); i += 4) {
                                result.add(current.getInt());
                            }
                        }
`
I use the iterator to read large values, but as the time goes, I found the disk io is so large which showed in the above picture, I really do not understand what happened. And the first code showed the java thread stack info.

**Comment by benalexau** [comment]
Can you please provide more information to assist understand and reproduce this issue? For example operating system, LmdbJava version, Java version, amount of RAM, size of database file, disk configuration (file system, RAID/JBOD configuration, SSD / NVMe / magnetic), amount of data you are trying to read back, what system profiling tools indicate is happening while running the application (eg [see here](https://serverfault.com/questions/2911/how-to-identify-i-o-bottlenecks-on-a-linux-server)) etc?

**Comment by alexBaiJW** [comment]
OS: CentOS Linux release 7.6.1810 (Core) 
lmdb.version:  0.8.1
JDK version: 1.8.0_66
amount of RAM: 64GB
size of database file: 9.4G
disk： SATA 
read: 16 thread to read a lot of kv
profiling tools: iotop

**Comment by alexBaiJW** [comment]
![image](https://user-images.githubusercontent.com/14144387/139812174-ec9f91fe-78a8-45ef-9eb9-0cc21b6ff16b.png)

**Comment by benalexau** [comment]
Is this still an issue?
