### ISSUE TITLE
lmdb file keep increasing and python read question！

### ISSUE THREAD

**Issue by xtuyaowu** [lmdbjava/lmdbjava#187]
1、lmdb use the same key to write data, why, the size of the folder will keep increasing, and then report an error.
     org.lmdbjava.Env$MapFullException: Environment mapsize reached (-30792)
    can not reuse the page？have used env.copy(copy, MDB_CP_COMPACT);

     my scenario is that the same key writes market data(update), and then another service uses the same key

    public void init(String lmdbPath, String dbName){
        try {
            final File path = new File(lmdbPath);
            env = create(PROXY_OPTIMAL)
                    .setMapSize(lmdbMaxSize * 1024 * 1024)
                    .setMaxDbs(lmdbDatabaseCount)
                    .setMaxReaders(lmdbDatabaseCount*2)
                    .open(path);
            db = env.openDbi(dbName, MDB_CREATE, DbiFlags.MDB_INTEGERKEY);
        } catch (Exception e) {
            throw new LmdbException("IO failure", e);
        }
    }

    public void putValueToDb(String key,String value) {
        long start = System.currentTimeMillis();
        try (Txn<ByteBuffer> txn = env.txnWrite()) {
            db.put(txn, bb(key), bb(value));
            txn.commit();
        }
        long end = System.currentTimeMillis();
        System.out.println("consume time："+(end-start)+"ms");
    }

2、Why can't the lmdb created by java be accessed by python?
      def initialize():
            env = lmdb.open("")  # 
            return env

      def search(env, sid):
            txn = env.begin()
            name = txn.get(str(sid).encode())
            return name

      def display(env):
            txn = env.begin()
            cur = txn.cursor()
           for key, value in cur:
                 print(key, value)
Thanks！

**Comment by benalexau** [comment]
How big is the database file on disk? The database will grow in size if you have a write transaction in flight while there are concurrent read transactions.

The wiki has a couple of pages that might help: 

https://github.com/lmdbjava/lmdbjava/wiki/Concurrency
https://github.com/lmdbjava/lmdbjava/wiki/Storage-Efficiency

**Comment by benalexau** [comment]
Closing this as there has been no response in over three months.
