### ISSUE TITLE
ByteBufferProxy$AbstractByteBufferProxy using illegal acces in JDK17

### ISSUE THREAD

**Issue by mehmetsalgar** [lmdbjava/lmdbjava#188]
Hi,

in my Akka project I am  getting the following Warning and they are advising that I should inform you...so here it is...

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy (file:/Volumes/Data/repo/org/lmdbjava/lmdbjava/0.7.0/lmdbjava-0.7.0.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by johanandren** [comment]
Looks like this was already discussed for quite a while in https://github.com/lmdbjava/lmdbjava/issues/42
