### ISSUE TITLE
Q: Supported number range for MDB_INTEGERKEY

### ISSUE THREAD

**Issue by jubax** [lmdbjava/lmdbjava#191]
Hi,

I have some questions about MDB_INTEGERKEY:

1) I guess MDB_INTEGERKEY is improving the performance when working with integer keys, right?

2) When using MDB_INTEGERKEY I need to set the byte order of buffers to native (`order(ByteOrder.nativeOrder())`), right?

3) I think I can use `int` and `long` for the keys. But what about 128 bit or 256 bit numbers (BigInteger)? Does this work, too?

Thank you!

**Comment by benalexau** [comment]
Full docs are at http://www.lmdb.tech/doc/group__mdb__dbi__open.html.

In summary, yes, use native order, it should improve performance (and likely disk space efficiency), and `long` would be correct for 64 bit systems (which is all LmdbJava supports). For 128/256 bit numbers you cannot use `MDB_INTEGERKEY`.

**Comment by jubax** [comment]
Thank you 👍
