### ISSUE TITLE
potentially dangerous resource / state handling

### ISSUE THREAD

**Issue by phraktle** [lmdbjava/lmdbjava#20]
Related to the fix made for #17 in d83d542627c0fb64d8f378cd522cad84d943fc84, I believe there might be further similar bugs in the codebase.

https://github.com/lmdbjava/lmdbjava/blob/119733e4ac753b8b8024a2afc237105660a54c3a/src/main/java/org/lmdbjava/Env.java#L367

Are resources properly deallocated if `mdb_env_open` fails?

(Disregard my earlier edit mentioning `Env#close`, that seems to make sense)

**Comment by benalexau** [comment]
I've captured the error and released the `MDB_env` on creation failure. Are there are other areas of concern?

**Comment by phraktle** [comment]
Thanks @benalexau, I'll close this, since the other thing I though I saw should be a non-issue...
