### ISSUE TITLE
Question: How many configurations (parameters or knobs) are available for users to tune for performance?

### ISSUE THREAD

**Issue by jimmy66688** [lmdbjava/lmdbjava#202]
Hi! every contributor,
I want to explore the performance potential of lmdbjava, as the title says, and I want to tune the options to improve performance? Which part of the code should I look at? And where is the entry point to the whole lmdbjava?

**Comment by benalexau** [comment]
There are few tuning settings available in LMDB. The vast majority of the real-world performance you will receive comes down to understanding your data write patterns, read patterns, optimal layout, transaction coordination (eg avoiding unnecessary transactions) and using the correct create-time flags (for example on `Env` and `Dbi`) to support this. These are not specific to LmdbJava but the underlying LMDB library. The [wiki](https://github.com/lmdbjava/lmdbjava/wiki) offers a lot of higher-level guidance on these topics and you can also ask on LMDB forums if unsure.
