### ISSUE TITLE
Unable to make field long java.nio.Buffer.address accessible

### ISSUE THREAD

**Issue by faust45** [lmdbjava/lmdbjava#205]
Hi! 
i am tying to use this lib from clojure on java 16.0.1 and got this:

Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @3b2bc5e8

please help!

**Comment by cheblin** [comment]
hello
just run your program with `--add-opens java.base/java.nio=ALL-UNNAMED` option. that's it

**Comment by wipfli** [comment]
I run into the same issue, thank @cheblin for posting here. Can I make a pull request and document this somewhere?
