### ISSUE TITLE
release of lmdbjava-0.8.3

### ISSUE THREAD

**Issue by cgilliard** [lmdbjava/lmdbjava#206]
The current version of the pom.xml is 0.8.2 and that doesn't support Mac M1 processors due to: https://github.com/lmdbjava/lmdbjava/issues/190 (which is fixed).

Is there any plan to cut a new release (lmdbjava-0.8.3) so that the M1 chips can be supported?

**Comment by Fierykev** [comment]
Was going to ask the same thing.  I need to be on the latest lmdb quite soon.  Sadly 0.8.2 is not compatible with it.

**Comment by cgilliard** [comment]
I created a pull request for this. https://github.com/lmdbjava/lmdbjava/pull/210

**Comment by benalexau** [comment]
Hi all. I can see you're keen for a new release so I will roll one out next week. I need to firstly go through the issue track to triage any bug reports, and I'd also like to merge any PRs where possible. If you have a moment to review the issue tracker or PRs it would speed things along, but I will do it myself over the next week or so and publish a release once done.

**Comment by benalexau** [comment]
LmdbJava 0.8.3 has been released and is [now available](https://repo1.maven.org/maven2/org/lmdbjava/lmdbjava/0.8.3/) from Maven Central.
