### ISSUE TITLE
Compatibility with Java 19 - Modularize? Minimizing use of unsupported JDK parts?

### ISSUE THREAD

**Issue by JorenSix** [lmdbjava/lmdbjava#208]
First of all thanks for releasing this library. For me it has really been working well but with the release of Java 19 there are a couple of changes which make it more difficult to work with this library. Mainly the access to `sun.nio.ch.DirectBuffer` has been cut off and in general is becomes more and more difficult to use unnamed modules.

I have taken it up to myself to modularize the package in a [lmdbjava fork](https://github.com/JorenSix/lmdbjava). Not much of the code itself has changed but some modifications were needed to allow module info to work (mainly for the test module). I also use Gradle to build the module.

To remove the dependency on `sun.nio.ch.DirectBuffer` I have resorted to reflection to access memory addresses. This means that still a JVM argument is needed and compatibility in the future is not guaranteed:

`--add-opens=java.base/java.nio=lmdbjava`

This is already an improvement over `--add-opens=java.base/java.nio=ALL-UNNAMED`

Please allow me to suggest a couple of enhancements which would make this work more easy to use and more future-proof:

* Modularizing would help with compatibility of JDK 19+
* Verifing dependencies on unsupported/unsafe JDK parts (especially the now difficult to acces `sun.nio.ch.DirectBuffer` )
* Update some of the dependencies to the latest versions
* Build the libraries in the lmdbjava project itself and ship them with the main library (e.g. for aarch64 (M1/M2) compatibility . I personally would not rely on GitHub Actions but perhaps cross compile them with Zig)

**Comment by benalexau** [comment]
I welcome any PRs that can address these issues. 

Please also see #42 for the long-term tracking issue for more modern JVM compatibility.

**Comment by pedrolamarao** [comment]
To allow Java modules to reference the `org.lmdbjava` package it should be sufficient to define the `MANIFEST.MF` attribute `Automatic-Module-Name`.

**Comment by benalexau** [comment]
An automatic module name was added in #213 and Zig cross compilation was added in #217. It's now three months since this ticket was opened and I am unclear what other specific action is being requested. As such I will close this ticket and repeat my [3 February](https://github.com/lmdbjava/lmdbjava/issues/208#issuecomment-1414459094) comment that PRs are welcome if there are other areas we can improve the project modularity.
