### ISSUE TITLE
Is lmdb has some problems which exists in go version?

### ISSUE THREAD

**Issue by lurais** [lmdbjava/lmdbjava#219]
Hello , is lmdbjava still has some problem which exists in go version, these problems is discribed here:  https://github.com/ledgerwatch/erigon/wiki/Criteria-for-transitioning-from-Alpha-to-Beta#switch-from-lmdb-to-mdbx

**Comment by wardle** [comment]
I'm not a maintainer but here are my thoughts.

LMDB is a C library. 

BoltDB was a port of the same approach in Go, but development was discontinued - the author moved to using SQLite. The code was forked in a separate project. 

Libmdbx was a version of LMDB that now appears archived and no longer under development in favour of something called Mithril which last time I looked appeared not to exist. 

As lmdbjava uses LMDB, it will inherit the same trade offs as the underlying library. That means it is well suited to certain workloads. For example, I use it for mostly immutable data stores. 

Personally, I'd worry less about the differences between one version and another, and instead get to the fundamentals - B-tree based databases suit certain types of workload while other technologies may not have such good read performance but have better write performance (eg WAL based stores). I guess we have to use the right technology for the job at hand... minor optimisations and tweaks are not going to change the fundamental characteristics here. 

As it is LMDB is actively maintained and well used. Have you seen [https://github.com/lmdbjava/lmdbjava/wiki/Is-LMDB-A-Good-Fit%3F](https://github.com/lmdbjava/lmdbjava/wiki/Is-LMDB-A-Good-Fit%3F)

**Comment by lurais** [comment]
> 
As I can see, lmdbjava is build base on lmdb, and the way of freelist management may cause some stability issues (refer to this:https://github.com/ledgerwatch/erigon/wiki/Criteria-for-transitioning-from-Alpha-to-Beta#switch-from-lmdb-to-mdbx),so should we pay attention to this problem? @wardle

**Comment by wardle** [comment]
As I said, I have no concerns about file growth, the need to specify memory map size ahead of time, or about free lists and churn in _my_ _use_ of lmdbjava / lmdb. As such, I don't share the concerns outlined in that post about MDBX. Unlike MDBX, LMDB is actively maintained upstream whereas I cannot find much about MDBX. That would be of greater concern to me. 

The combination of lmdbjava/LMDB has been fantastic for the problems I need to solve. Depending on your need, you may make a different choice, and prefer different storage technologies such as LSM.

**Comment by lurais** [comment]
> As I said, I have no concerns about file growth, the need to specify memory map size ahead of time, or about free lists and churn in _my_ _use_ of lmdbjava / lmdb. As such, I don't share the concerns outlined in that post about MDBX. Unlike MDBX, LMDB is actively maintained upstream whereas I cannot find much about MDBX. That would be of greater concern to me.
> 
> The combination of lmdbjava/LMDB has been fantastic for the problems I need to solve. Depending on your need, you may make a different choice, and prefer different storage technologies such as LSM.

Yes , I will try to fix some problems in the tech when I want to use some technologies ,and if it is suit you that's ok. And I don't think it good to change to another technology without any trying to fix when some problems meet.

**Comment by wardle** [comment]
I'd suggest this issue is closed. Any issues are either a fundamental feature of the underlying design (copy-on-write, B-tree) or implementation. In particular, the former will not be changed, and the latter is an upstream issue that should be [raised upstream](https://git.openldap.org/openldap/openldap).
