### ISSUE TITLE
Why does LMDB need to know how large our DB might be?

### ISSUE THREAD

**Issue by siddhsql** [lmdbjava/lmdbjava#224]
w.r.t. [this](https://github.com/lmdbjava/lmdbjava/blob/master/src/test/java/org/lmdbjava/TutorialTest.java#L95):

```
final Env<ByteBuffer> env = create()
        // LMDB also needs to know how large our DB might be. Over-estimating is OK.
        .setMapSize(10_485_760)
        // LMDB also needs to know how many DBs (Dbi) we want to store in this Env.
        .setMaxDbs(1)
        // Now let's open the Env. The same path can be concurrently opened and
        // used in different processes, but do not open the same path twice in
        // the same process at the same time.
        .open(path);
```

how can someone know in advance how large the DB will be? that is not a realistic constraint. what happens when size of DB exceeds this limit? similarly what happens when # of DBs exceeds `setMaxDbs`?

**Comment by siddhsql** [comment]
http://www.lmdb.tech/doc/group__mdb.html#gaa2506ec8dab3d969b0e609cd82e619e5

**Comment by wardle** [comment]
I'm not the author of lmdb or lmdbjava but here are my thoughts. 

It's a function of how lmdb works. 

For many use cases this is not an issue at all. The size sets the memory map size and uses a sparse file so it doesn't take up as much space as you set, only that you use. 

If it's an issue (it isn't for my use cases) you can detect when size goes above a certain threshold and copy/create a new larger file based db. Others use rolling databases for time series data or use for archival / immutable data.

**Comment by benalexau** [comment]
> If it's an issue (it isn't for my use cases) you can detect when size goes above a certain threshold and copy/create a new larger file based db.

You just need to re-open the database with larger settings if required. I've never encountered it as an issue in practical situations. My larger workloads have a "data collection" phase where it's basically random writes, then an end of day write of the database so the keys are in perfect order. That reduces the size of the long-term file as well.
