### ISSUE TITLE
Entries not having expected values

### ISSUE THREAD

**Issue by edh5623** [lmdbjava/lmdbjava#225]
I am seeing a symptom where I am inserting a positive Long value but when I retrieve it it is a negative Long value. It happens only very rarely. Has anyone seen this symptom?

LMDB Version: 0.8.3
Mac OS: Ventura 13.3.1 (a)
Scala Version (Scala calling Java API): 2.12.15
Java Version: Java 8 (OpenJDK 1.8)

**Comment by wardle** [comment]
Lmdb stores bytes. What buffer implementation are you using and have you checked how you are serialising your values eg are you mixing up unsigned vs signed in writing then reading to your buffer?

**Comment by edh5623** [comment]
I am using the ByteBuffer in java.nio. All of the values I am inserting are Scala Long values that are always positive and I am reading out the same.

I attempted to rebuild the LMDB with only the values I was seeing this symptom with but the problem was not reproducible.

**Comment by benalexau** [comment]
It surprises me this would be happening. I suggest having a look at the [Verifier](https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/Verifier.java) code if you'd like a longer example of persisting and retrieving `long` primitives.

**Comment by edh5623** [comment]
FYI Apple M1 chip exhibits this symptom but Intel does not.

**Comment by benalexau** [comment]
Can you please try with LmdbJava 0.9.0.
