### ISSUE TITLE
New release date?

### ISSUE THREAD

**Issue by paul-snively** [lmdbjava/lmdbjava#226]
First, thank you all for all of your hard work on these bindings!

We have a number of developers now who are Apple Silicon based, so I was wondering if there's some anticipated date on which a new release is expected to be cut, since the 0.8.3 release does not include Apple Silicon support.

Thanks again!

**Comment by benalexau** [comment]
I have released 0.9.0.

**Comment by paul-snively** [comment]
Thank you so much for this!

Unfortunately, one of our developers on Apple Silicon, when trying to use the new 0.9.0 dependency, gets:

```
rnode.bootstrap   | 2023-12-06 18:26:40,299 [main] ERROR coop.rchain.node.Main$ - Unhandled exception in thread main
rnode.bootstrap   | java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
rnode.bootstrap   |     at jnr.ffi.provider.InvalidProvider$1.loadLibrary(InvalidProvider.java:49)
rnode.bootstrap   |     at jnr.ffi.LibraryLoader.load(LibraryLoader.java:420)
rnode.bootstrap   |     at jnr.ffi.LibraryLoader.load(LibraryLoader.java:399)
rnode.bootstrap   |     at org.lmdbjava.Library.<clinit>(Library.java:81)
rnode.bootstrap   |     at org.lmdbjava.Env$Builder.open(Env.java:580)
```

I've manually downloaded the published `.jar`s for jnr-ffi, jnr-jffi, and lmdbjava, extracted them, and honestly, everything looks in order. I've used the Ammonite REPL for Scala, imported lmdbjava from the central Maven repo, and walked through the steps of the tutorial to create a database, insert data, retrieve data, etc. successfully, but I'm on an X86_64 macOS box. Any advice would be welcome.

Thanks again!

**Comment by paul-snively** [comment]
> Mac Studio (M1 Max)

It may be worth noting my colleague is on an M2 Mac.

**Comment by benalexau** [comment]
Can you please open a separate issue as this is unrelated to the original issue of the release date. Thanks.
