### ISSUE TITLE
BadReaderLockException on concurrent read transactions

### ISSUE THREAD

**Issue by kamstrup** [lmdbjava/lmdbjava#23]
Opening two concurrent read txns gives an error. Here's a unit test to reproduce (for TxnTest.java):
```java
  @Test
  public void readOnlyConcurrentTxnAllowedInReadOnlyEnv() {
    env.openDbi(DB_1, MDB_CREATE);
    final Env<ByteBuffer> roEnv = create().open(path, MDB_NOSUBDIR,
            MDB_RDONLY_ENV);
    Txn<ByteBuffer> txn1 = roEnv.txnRead();
    Txn<ByteBuffer> txn2 = roEnv.txnRead();
    assertThat(txn1, is(notNullValue()));
    assertThat(txn2, is(notNullValue()));
    assertThat(txn1, is(not(sameInstance(txn2))));
    assertThat(txn1.getId(), is(not(txn2.getId())));
    txn1.close();
    txn2.close();
  }
```

Stacktrace:
```
org.lmdbjava.Txn$BadReaderLockException: Invalid reuse of reader locktable slot (-30783)

	at org.lmdbjava.ResultCodeMapper.<clinit>(ResultCodeMapper.java:54)
	at org.lmdbjava.Env$Builder.open(Env.java:369)
	at org.lmdbjava.TxnTest.before(TxnTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)


Process finished with exit code 255
```

**Comment by kamstrup** [comment]
Note that the stacktrace is actually completely wrong - as we also discussed in another bug report.

**Comment by kamstrup** [comment]
Hmmm, maybe I am just not understanding this properly... Reading some of the docs I get the impression that the same thread can only have one txn at a time

**Comment by krisskross** [comment]
Correct. You can change this behaviour with the MDB_NOTLS flag.

From the [LMDB docs](http://lmdb.tech/doc).

> A thread can only use one transaction at a time, plus any child transactions. Each transaction belongs to one thread. See below. The MDB_NOTLS flag changes this for read-only transactions.

**Comment by kamstrup** [comment]
Thanks for the clarification @krisskross !

**Comment by phraktle** [comment]
@benalexau / @krisskross any thoughts on the "pink elephant" stack trace here? seems like a different case from the zero-buffer problem discussed earlier.

**Comment by benalexau** [comment]
I added some logic to detect and report upon illegal creation of multiple `Txn`s in a single thread. There is also a convenient new `Env.txn()` method to return the current thread's parent `Txn`, which may be useful if people want to access the thread's `Txn` without expressly passing it around.

**Comment by phraktle** [comment]
@benalexau do you have any insights on how to avoid these corrupted stack traces in a systematic way? very confusing, when it happens...

**Comment by benalexau** [comment]
I'm unaware of any systemic avenue we could pursue here. I'm happy to defensively encode the LMDB rules on the Java side where possible, but there's a limit to how many misuse scenarios we can actively guard against given LMDB's extremely high level of flexibility and our desire to not sacrifice performance. For example, we could use some proxying approaches to detect use of a `ByteBuffer` after the `Txn` ends, but this would result in an overhead for every buffer call. Then again we could only do this if `Env.SHOULD_CHECK == true`, so perhaps it's reasonable for development and test time.

**Comment by phraktle** [comment]
What I'm fundamentally missing here, is what's causing a corrupted stack trace in the first place. A native library returning with an error code should not cause this type of corruption. Adding pre-call checks is just a workaround: an undefined number of other scenarios may remain where there's an error returned by the library. Under no circumstances should these result in a corrupted stack trace. So I think we need to dig deeper here and figure out what's causing it.

**Comment by kamstrup** [comment]
Opened https://github.com/lmdbjava/lmdbjava/issues/25 to keep track of the stack trace issues, so we have an open bug users can discover if they find issues with their stacktraces.

**Comment by phraktle** [comment]
If we're going to go the extra mile and use our own ThreadLocal Txns, I would suggest always forcing MDB_NOTLS and using something like the below code.

So basically `Env` would automatically recycle read transactions (like MDB does by default), but also allow transparently creating multiple transactions per thread. Closing the `Txn` should call `release`.

This would basically avoid people running into the problem reported in this ticket, and also provide a performant approach when using MDB_NOTLS mode (since there's still caching).

```
private final ThreadLocal<Txn<T>> cachedTx = new ThreadLocal<>();

private Txn<T> acquireReadTransaction() {
    Txn<T> tx = cachedTx.get();
    if (tx == null) {
        tx = env.txnRead();
    } else {
        cachedTx.set(null);
        tx.renew();
    }
    return tx;
}

private void releaseReadTransaction(Txn<T> tx) {
    if (cachedTx.get() == null) {
        tx.reset();
        cachedTx.set(tx);
    } else {
        tx.abort();
    }
}
```

**Comment by benalexau** [comment]
Can you maybe package this up into a PR (including associated `Env` `ThreadLocal` use changes, removing the unwanted `ThreadHasTransactionException` if desired etc)?

**Comment by phraktle** [comment]
Most likely not this week, travel / meetings :)

**Comment by phraktle** [comment]
In the meantime, do you agree with this in principle? Do you see any issues with the approach?

We have been successfully using this approach in our wrapper around `lmdbjava`, but this change would mean that you could only use LMDB in NOTLS mode (but with the same basic caching approach, just better usability).

**Comment by benalexau** [comment]
Well I agree we are at a stage now where both the native library and Java side each duplicate transaction handle reuse and `ThreadLocal` awareness. It would seem simpler to just have one side do it, so I am not opposed to doing it on the Java side if we keep the code elegant.

Reading the `MDB_NOTLS` documentation against [`mdb_env_open`](http://104.237.133.194/doc/group__mdb.html#ga32a193c6bf4d7d5c5d579e71f22e9340) does make me wonder whether we're biting off more than we can chew, though, given the write transactions must also be serialized?

**Comment by benalexau** [comment]
I have just reverted of most of the Txn thread guard work.

Upon further reflection and working on my own LmdbJava-reliant applications in recent days, I can see that `ThreadLocal`-enforced single transactions per thread will impose unreasonable restrictions in certain cases. There's a lot of flexibility provided by `MDB_NOTLS` if users know what they're doing (cf @phraktle's wrapper code), and as such it seems unwise to block advanced usage via a `ThreadLocal` in lower-level types such as `Env`.

**Comment by phraktle** [comment]
So overall, do you feel that `lmdbjava` should internally apply the trick I proposed above (using `MDB_NOTLS` with a more convenient Txn recycling than the default), or is this something that library users should work out on their own?

**Comment by benalexau** [comment]
My primary concerns are code complexity (thus maintenance effort) and blocking paths for advanced users who determine they require a different model for `Txn` management (eg their own reuse approaches, or multiple `Txn`s per thread, or just the default native library managed handle reuse etc).

I am not opposed to adding a strategy interface to LmdbJava to simplify alternate transaction handle allocators. For example, it would receive callbacks on `Env` creation, `Txn` acquisition and `Txn` close. If we had this users would be able to use standard `Env` methods to acquire and dispose of transactions without having to know about handle recycling internals. The applicable strategy could just be set in the `Env.Builder`. I would not mind if a `ThreadLocalTxnAllocator` was shipped with LmdbJava, beside the default `NativeLibTxnAllocator` (just quick example names). Does this seem a reasonable way forward?
