### ISSUE TITLE
Page Full Exception on Apple Silicon

### ISSUE THREAD

**Issue by edh5623** [lmdbjava/lmdbjava#231]
Attempting to build a database and running into this exception:

`org.lmdbjava.LmdbNativeException$PageFullException: Page has not enough space - internal error (-30786)` 

This occurred on a machine with an M1 chip. Using the same data to build this database on a mac with an intel chip did not produce this error.
 
There are 19,303,621 entries being inserted into the database. The keys are the max key size and the maximum value size is 4544 bytes. There is more than enough free storage on the machine to hold the resulting database.
 
LMDB Version: 0.9.0
Scala Version (Scala calling Java API): 2.12.15
Java Version: Java 8 (OpenJDK 1.8)

**Comment by justjohn2001** [comment]
Locally compiling and using a liblmdb.so based on the most recent version (v0.9.31) solved this for me.

**Comment by edh5623** [comment]
> Locally compiling and using a liblmdb.so based on the most recent version (v0.9.31) solved this for me.

This also worked for me. Thank you!
