### ISSUE TITLE
Env$MapFullException while deleting data from cursor

### ISSUE THREAD

**Issue by cdprete** [lmdbjava/lmdbjava#236]
Hello.
I'm using lmdbjava 0.8.3 and while iterating over a Cursor to delete some data, I constantly get
```
org.lmdbjava.Env$MapFullException: Environment mapsize reached (-30792)
        at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:86)
        at org.lmdbjava.Cursor.delete(Cursor.java:124)
```

The code is the following:
```kotlin
    dbi.openCursor(txWrite!!).use {
            while(isRunning && it.next()) {
                if(it.key().marketCode in inactiveMarketCodes || isIgnored(it.key().statisticType, valueType(it.key(), it.`val`()))) {
                    it.delete()
                }
            }
        }
```
Can you provide some insights on why this is happening?
I don't even get why the map size should be involved here, since I'm just reading data...

Kind regards and thanks.

**Comment by at055612** [comment]
I'm not the maintainer, just a fellow lmdbjava user, so stand to be corrected.

You are not just reading data you are deleting entries in a write txn.  LMDB is copy-on-write so if you are near your map size then it probably has no room for both the dirty and new pages.

I think this answers your specific issue
https://openldap-technical.openldap.narkive.com/W13bEpnY/lmdb-mdb-map-full-doesn-t-allow-deletions

and for a better understanding of how LMDB works see
https://schd.ws/hosted_files/buildstuff14/96/20141120-BuildStuff-Lightning.pdf

**Comment by at055612** [comment]
My understanding is that there is no penalty (on linux) for setting it bigger than you need, i.e. set it <= the amount of free space on disk or like @wardle says, set it to the max size you think you will need (but this is hard to gauge given the COW and free page reuse).  It can be set to Terrabytes in size and bigger than RAM.  Linux will not allocate all that space up front, but I think Windows/MacOS may do.  If you have >1 lmdb envs on the disk then like you say, you will need to size each one so they all have room.

Be aware of how the lmdb file grows and re-uses (or not) free space inside it.  It can never shrink, only grow or reuse the free space from deletes.  However, if you have read txns open when writing then the write txn cannot reuse free space so this can lead to a lot of growth on disk.  This is particularly relevant if you are using it for any kind of queue with high churn.  If you are concerned about size on disk then you need to put concurrency measures in place to make writes block reads.  It is a trade off between performance and file size.

**Comment by cdprete** [comment]
> My understanding is that there is no penalty (on linux) for setting it bigger than you need, i.e. set it <= the amount of free space on disk or like @wardle says, set it to the max size you think you will need (but this is hard to gauge given the COW and free page reuse). It can be set to Terrabytes in size and bigger than RAM. Linux will not allocate all that space up front, but I think Windows/MacOS may do. If you have >1 lmdb envs on the disk then like you say, you will need to size each one so they all have room.
> 
> Be aware of how the lmdb file grows and re-uses (or not) free space inside it. It can never shrink, only grow or reuse the free space from deletes. However, if you have read txns open when writing then the write txn cannot reuse free space so this can lead to a lot of growth on disk. This is particularly relevant if you are using it for any kind of queue with high churn. If you are concerned about size on disk then you need to put concurrency measures in place to make writes block reads. It is a trade off between performance and file size.

Hi @at055612 
Thank you for the detailed response.

> This is particularly relevant if you are using it for any kind of queue with high churn
Indeed I'm (something like 1M entries per second per shard).

>  If you are concerned about size on disk then you need to put concurrency measures in place to make writes block reads
Then reads would always be blocked :D 

Is there no way to recompact the space?

**Comment by at055612** [comment]
I think the only way to compact space is using mdb_copy (`org.lmdbjava.Env#copy` with `org.lmdbjava.CopyFlags#MDB_CP_COMPACT` in lmdbjava) which copies the whole db into a new one and compacting at the same time.  This obviously means the app having to switch between different envs and possibly use a 3rd env while the copy happens.

http://www.lmdb.tech/doc/man1/mdb_copy_1.html

I you haven't already, I recommend reading the wiki on here https://github.com/lmdbjava/lmdbjava/wiki and also looking through the closed issues as some of the answers are very helpful in understanding how best to use LMDB(java).  LMDB is very good but you have to understand its limitations/restrictions and work effectively with them.

One possibility is to have the various java threads handing off work to one thread that does all lmdb writes/reads in long running txns so that space can be fully reused as it is the only txn.  It is also worth ensuring that you do as little work as possible inside a txn so the txn is as short as possible, e.g. do (de)serialisation outside the txn.

**Comment by cdprete** [comment]
> I think the only way to compact space is using mdb_copy (`org.lmdbjava.Env#copy` with `org.lmdbjava.CopyFlags#MDB_CP_COMPACT` in lmdbjava) which copies the whole db into a new one and compacting at the same time. This obviously means the app having to switch between different envs and possibly use a 3rd env while the copy happens.
> 
> http://www.lmdb.tech/doc/man1/mdb_copy_1.html
> 
> I you haven't already, I recommend reading the wiki on here https://github.com/lmdbjava/lmdbjava/wiki and also looking through the closed issues as some of the answers are very helpful in understanding how best to use LMDB(java). LMDB is very good but you have to understand its limitations/restrictions and work effectively with them.
> 
> There is some good info in this issue #119.
> 
> One possibility is to have the various java threads handing off work to one thread that does all lmdb writes/reads in long running txns so that space can be fully reused as it is the only txn. It is also worth ensuring that you do as little work as possible inside a txn so the txn is as short as possible, e.g. do (de)serialisation outside the txn.

Thank you for the reply.

I already run long living write transactions (one per shard, committed roughly every 20s), but I need to have parallel/concurrent reads as well and committing a write tx on every message is not an option (it's tooo slow).

**Comment by at055612** [comment]
To quote from #119 
>Personally most of my LMDB applications open one very long-lived transaction and it's used for **both reads and writes**.

You can have a single java thread that holds the lmdb writeTxn open for long periods.  It just pulls work items off a concurrent queue and executes them in that writeTxn.  These items could be reads or writes that have been put on the queue by reader or writer threads.  This does make it more complicated and serialises all work to one thread, but will allow reads to see uncommitted writes and will stop growth of the lmdb env.  If you do this, the work items need to contain already serialised keys/values so the single thread talking to lmdb is doing as little work as possible.

It is all about trade offs.

Also, if you are using lmdb for some kind of queue with an always incrementing key, consider using `org.lmdbjava.PutFlags#MDB_APPEND` on the puts as this can speed up writes considerably.

**Comment by cdprete** [comment]
Hi @at055612.

The weird thing is that the exception happens from time to time even when the disk is not full at all (e.g.: only 28% is used).
Nevertheless, I'll try to figure it out.
Thank you for all the insights.
