### ISSUE TITLE
Example usage of MDB_MULTIPLE

### ISSUE THREAD

**Issue by harrigan** [lmdbjava/lmdbjava#24]
Thank you for creating LmdbJava!

I'm trying to adapt your `tutorial5()` method to use the MDB_MULTIPLE flag to store the three values in one call. The LMDB documentation says that the data argument must be two `MDB_vals`. Is this possible using LmdbJava?

**Comment by benalexau** [comment]
Quoting the [docs](http://lmdb.tech/doc/group__mdb.html#ga1f83ccb40011837ff37cc32be01ad91e) for the benefit of others finding this ticket:

> MDB_MULTIPLE - store multiple contiguous data elements in a single request. This flag may only be specified if the database was opened with MDB_DUPFIXED. The data argument must be an array of two MDB_vals. The mv_size of the first MDB_val must be the size of a single data element. The mv_data of the first MDB_val must point to the beginning of the array of contiguous data elements. The mv_size of the second MDB_val must be the count of the number of data elements to store. On return this field will be set to the count of the number of elements actually written. The mv_data of the second MDB_val is unused. 

This is currently unsupported by LmdbJava.

Internally LmdbJava's `BufferProxy` populates `MDB_val`s with the required size (length) and pointer to data. We could amend our approach to always reserved space for two `MDB_val`s, but the different `BufferProxy` implementations would still require a way to determine the size of each data element and the count of data elements. The main buffers (eg `DirectBuffer`, `ByteBuffer`) do not have a field to communicate such details, so we'd need to overload `Cursor.put(T, T, PutFlags...)` to support these additional arguments and pass them through to `BufferProxy` via amended `in` methods (I'd suggest just adding the data count and element size to each `in` method and the former remains `1` for all existing calls).

Overall it's a reasonable amount of complexity and effort to make this possible. Can I ask about your use case?

**Comment by harrigan** [comment]
Thank you for the clarification.

I am bulk loading an adjacency list for a large graph (key = vertex, data = neighbours). I have the complete list of neighbours for each vertex in sorted order. I append each neighbour using a call to `put` with the `PutFlags/MDB_APPENDDUP` flag.

The graph is dense: I have many more edges than vertices. I wanted to check if I could make one call to `put` per vertex rather than per edge and what impact that would have on performance.

**Comment by benalexau** [comment]
I'll close this ticket, as I've created a new one (#28) to track the new feature request.
