### ISSUE TITLE
Can't build with maven

### ISSUE THREAD

**Issue by vtkstef** [lmdbjava/lmdbjava#29]
ssantoro@stefanows:~/var/tmp/lmdbjava [master|…44] 
09:17 $ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /home/ssantoro/.sdkman/candidates/maven/current
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-36-generic", arch: "amd64", family: "unix"
ssantoro@stefanows:~/var/tmp/lmdbjava [master|…44] 
09:17 $ mvn package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.lmdbjava:lmdbjava:0.0.4-SNAPSHOT: Could not find artifact au.com.acegi:acegi-standard-project:pom:0.0.8-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.lmdbjava:lmdbjava:0.0.4-SNAPSHOT (/home/ssantoro/var/tmp/lmdbjava/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.lmdbjava:lmdbjava:0.0.4-SNAPSHOT: Could not find artifact au.com.acegi:acegi-standard-project:pom:0.0.8-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
ssantoro@stefanows:~/var/tmp/lmdbjava [master|…44] 
09:17 $

**Comment by benalexau** [comment]
That's caused because the parent POM is in a snapshot repository at present. Try `mvn --settings .travis-settings.xml test` and it should be OK.

I'm unsure why you're trying to build in the first place, but if it's just to get an up-to-date JAR you can find these in our snapshot repository [here](https://oss.sonatype.org/content/repositories/snapshots/org/lmdbjava/lmdbjava/).

**Comment by vtkstef** [comment]
thanks! that did it
