### ISSUE TITLE
How to run on CentOS 6.6

### ISSUE THREAD

**Issue by patriknw** [lmdbjava/lmdbjava#33]
What is your advice for running lmdbjava on CentOS 6.6?

The problem is that glibc is too old:
```
Caused by: java.lang.UnsatisfiedLinkError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/lmdbjava-native-library-2822335035865031061.so)
```

Can we install glibc on CentOS 6.6? Do you know of any good instructions of how to do that?

Or should we build our own version of lmdbjava and it's native dependencies? How would we do that?

**Comment by benalexau** [comment]
You have two main options:

1. Install LMDB as a package via your OS package manager. A [quick Google](https://pkgs.org/download/lmdb(x86-64)) suggests this is available. Once installed, you should be able to start LmdbJava and have it use the OS-provided version by setting the `lmdbjava.disable.extract` system property (see [Library.java](https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/Library.java)).

2. Try building the [LmdbJava Native](https://github.com/lmdbjava/native) JAR. If it compiles for you, the result will be a JAR that you can specify as a dependency for a subsequent LmdbJava `mvn clean package`.

**Comment by ktoso** [comment]
Thanks @benalexau :)
For reference, I checked on Centos 6.5 and building from source is rather painless, for reference these are the steps I did (in case it might help anyone):

```
# system I used: 
[root@ip-172-31-47-191 native]#  rpm --query centos-release
centos-release-6-5.el6.centos.11.2.x86_64

# resulting artifact, to be used:
[root@ip-172-31-47-191 native]# ls linux-x86_64/target/*jar
linux-x86_64/target/lmdbjava-native-linux-x86_64-0.9.18-4-SNAPSHOT.jar


# steps:
    1  yum install gcc
    2  yum install git-core
    3  git clone https://github.com/lmdbjava/native

    8  git submodule update --init

# install maven (via yum)
   13  sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
   14  sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
   15  sudo yum install -y apache-maven
   16  mvn --version

# get java 8
   18  cd /opt/
   19  wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz"
   20  tar xzf jdk-8u111-linux-x64.tar.gz
   21  cd /opt/jdk1.8.0_111/
   22  alternatives --install /usr/bin/java java /opt/jdk1.8.0_111/bin/java 2
   23  alternatives --config java 

# build the native things:
   31  cd native/
   35  export JAVA_HOME=/opt/jdk1.8.0_111/
   41  yum provides *x86_64-w64-mingw32-gcc
   42  yum install mingw64-gcc-4.9.2-1.el6.x86_64
   43  mvn clean install
```

I'd consider this closed, let's re-open in case we find any more specific issue.
Thanks @benalexau 👍

**Comment by patriknw** [comment]
Thanks!

**Comment by benalexau** [comment]
Thanks for the detailed write up. Glad you got it working!

**Comment by pulasthi** [comment]
I got the same issue with Red Hat Enterprise Linux Server release 6.9, and was able to resolve it buy building the native library locally, 

Just to add a note "git submodule update --init" might not fetch the files if you already have a "lmdb" folder created, so if there is such a file delete it before execution "git submodule update --init". Adding it here just in case someone else runs into the same issue. 
Thanks
