### ISSUE TITLE
Growing map size

### ISSUE THREAD

**Issue by dzhoou** [lmdbjava/lmdbjava#34]
Is there an api for map (auto)resize? Currently It looks like lmdb just gives up writing when the size limit is reached.

**Comment by benalexau** [comment]
No, there isn't. The map size is set at `Env` creation time via the C function [mdb_env_set_mapsize](http://lmdb.tech/doc/group__mdb.html#gaa2506ec8dab3d969b0e609cd82e619e5). Please see the link for restrictions on changing the map size. What I generally do is just use a map size that is the greater of (a) my expected data size and (b) 50% bigger than the current actual size.

**Comment by dzhoou** [comment]
Thanks for the link. I do work with a constantly increasing database, so if I write a synchronized method to call this C function, it looks like I could indeed expand the map on-demand.

**Comment by phraktle** [comment]
@dzhoou why don't you just set the maximum size to something that you deem sufficient, and let it grow? :)

**Comment by dzhoou** [comment]
@phraktle Just realized the file can grow on linux, I was testing on Windows and upon creation, the db file can only have one size... that is the maximum size declared :)

**Comment by dzhoou** [comment]
Another thing, I see exception being thrown when trying to delete a key not existing in the database, Aside from doing a db.get to check, is there a more elegant (better-performing) way to do "deleteIfExists"?

**Comment by benalexau** [comment]
@dzhoou can you please close this ticket if you're happy with the info. Thanks.

**Comment by dzhoou** [comment]
Sure thing, I'll open another one if anything comes up. Thanksa gain!

**Comment by benalexau** [comment]
No worries. We're happy to help folks using LmdbJava and tickets are the best way to get a quick response. :-)
