### ISSUE TITLE
Enumerating all dbs in an environment

### ISSUE THREAD

**Issue by scottcarey** [lmdbjava/lmdbjava#37]
I need to open an environment and discover all of the databases.  From what I understand, the database names are stored in the default, nameless db.  But what encoding?  Creating a db ends in a native method stub passing a String...  UTF-8?

````java
    Txn<ByteBuffer> txn = env.txn(null);
    env.openDbi(null).iterate(txn).forEachRemaining(kv -> {
      ByteBuffer keybytes = kv.key();
      String key = ??? 
    });
````

It would probably be useful to add both the ability to retrieve all dbi names to `Env`, as well as the ability to return all `Dbi`s in an `Env` as a `Map<String, Dbi>`.  The LMDB docs suggest that it is good practice to retrieve and re-use these anyway.

So I suppose this is mostly a question, but also a minor feature request.

**Comment by scottcarey** [comment]
Experimenting with it, UTF-8 seems to work, even for strings containing surrogate pairs.

Because openDbi creates its own transaction, and read-only transactions can not nest, the below is the solution I came up with for getting a `Map<String, Dbi>` that works for both read only and read/write environments:

````java
    Dbi<ByteBuffer> catalog = env.openDbi(null);  // creates its own transaction internally
    Txn<ByteBuffer> txn = env.txnRead();
    List<String> names = new ArrayList<>();
    try (CursorIterator<ByteBuffer> ci = catalog.iterate(txn)) {
      ci.forEachRemaining(kv -> {
        ByteBuffer keybb = kv.key();
        byte[] keybytes = new byte[keybb.remaining()];
        keybb.get(keybytes);
        String key = new String(keybytes, StandardCharsets.UTF_8);
        names.add(key);
      });
    }
    txn.commit();
    Map<String, Dbi<ByteBuffer>> dbis = new HashMap<>();
    for (String name: names) {
      dbis.put(name, env.openDbi(name));
    }
    return dbis;
````

**Comment by scottcarey** [comment]
Although UTF-8 works for me locally (MacOSX + JDK 1.8.0_45), it is unclear why.  It is possible that when the String crosses over to native code, that the system default encoding or similar is used, and thus it is system dependent.

**Comment by benalexau** [comment]
Thanks for the solution and associated PR.

Currently LmdbJava makes no encoding assumptions. I am concerned about changes which specify UTF-8 because it means we are now making an assumption that not only impacts existing LmdbJava-created databases, but more importantly its compatibility with LMDB databases produced independently of LmdbJava.

For example, I have several LMDB databases that are shared between C++ and Java processes. I also use a third party market data system which encodes using Windows character sets. As such even in my own applications there are a variety of character sets in flight.

Encoding choices are not confined to database names. As LMDB only deals with `byte[]`s and offsets, users already have to decide on various key and value layout issues (eg string encoding: length prefix or `\0` suffix or fixed length; string encoding: character set; number encoding: Endianness) or select a serialization library. Given these end user decisions are already unavoidable, requiring UTF-8 in database names doesn't feel consistent.

I can see the tooling advantages of iterating a LMDB `Dbi` list. However tooling will run into a challenge when it wishes to display the keys and values, as it doesn't know how they're encoded. Even assuming they're strings won't work as strings can be encoded in so many ways. It's more likely the tooling would support a particular serialization format, but this makes the tool fairly application-specific and it would seem reasonable in such a case to require UTF-8 database names.

Put differently, I think LmdbJava should be encoding agnostic so it has full compatibility with LMDB databases produced by LMDB on different processors, operating systems and language wrappers. There's a good case for higher-level tooling, but it feels like a higher level library given the keys and values require significant encoding awareness anyway.

@krisskross do you have any thoughts on this?

**Comment by scottcarey** [comment]
> Encoding choices are not confined to database names.

Database names do not have an encoding choice.  They are the only place that this library takes a String for a key, and not a raw byte form, and thus the user has has _no control over_ the encoding in the code, leaving it up to what the JDK implicitly wants to do, which varies wildly from system to system and even across different versions of JDK 8 on Linux.

I'll change my PR to add a second method that gives the user some control over the database name key encoding, and leave the original one there.

As for the tooling use cases, those are only an example subset of uses of this functionality.  Even if you don't know the encoding of the K/V data, you can still build useful tooling (ever used unix 'file' ?).  In the real world I can usually detect common types or have metadata that additionally helps with tooling.  Even without that, being able to know what databases are there, how many keys are in each, and what the average size of each key and value are can be extremely useful.

Aside from tooling, my most important use case for iterating over the Dbis boils down to building arbitrary K/V indexes in back end jobs (think Spark/Hadoop/Machine Learning/Etc) and transmission of these in bulk to front-end servers that swap the indexes atomically.  The transfer of these, and the framework that swaps data sets, knows _nothing_ about the serialization and only needs to know the names of the databases and be able to acquire their corresponding Dbi instance and replace existing ones of the same name.   Analogous to how rsync doesn't need to know about the contents of the file, just its path and raw data.

Lastly, every other K/V library I use that supports named databases/indexes can iterate over the names.

**Comment by scottcarey** [comment]
The last update to the PR gives the user the ability to pass in an arbitrary `Charset`, and leaves the existing method signatures alone, so that they use the system default encoding.

**Comment by krisskross** [comment]
I think its more consistent to change the type of the `Dbi` construction argument `name` from `String` to `byte[]`. And it seems like its something that we need to do?

I could appreciate `allDbiNames` but the current implementation would not work for names with different encodings. But maybe just change the return value to a list of `byte[]`.

This would make the API consistent and push encoding to the user. 

I'm not sure about a `openAllDbi` but I don't have a strong argument against it. It just seem a little too application specific for my taste.

**Comment by benalexau** [comment]
I have implemented the changes suggested by @krisskross. Hope this helps with your use case, @scottcarey.

**Comment by scottcarey** [comment]
>  think its more consistent to change the type of the Dbi construction argument name from String to byte[]

Most consistent would be to change it to `T`, the buffer type but that runs into problems and is awkward.  

> I could appreciate allDbiNames but the current implementation would not work for names with different encodings. But maybe just change the return value to a list of byte[].

That would be simplest, though I assume that almost all use cases will use the same encoding across all dbis in an Env.  Furthermore, its not like getting a list of byte[] is any better if the encodings differ between values -- there is no way to tell which is which.   Having the byte[] variant available is important, however -- one can use names that aren't strings.

> I'm not sure about a openAllDbi but I don't have a strong argument against it. It just seem a little too application specific for my taste.

From what I understand, it is the best practice to open all the databases at the start of the application and re-use them anyway.  Use cases where they need to be opened/closed and managed more closely are not very common (hence, the comment on dbi_close).   Given access to all the names, it won't be hard to do this on my own though.

> I have implemented the changes suggested by @krisskross. Hope this helps with your use case, @scottcarey.

Yeah, it is enough.  I'll write my own helper to open everything up and decode the names.  It would be nice if that code was in here (I think others could use it too), but its not hard to do now that there is access to the bytes.

**Comment by scottcarey** [comment]
> I have implemented the changes suggested by @krisskross. Hope this helps with your use case, @scottcarey.

Also, your changes run into the problem you brought up with my earlier PR variant:

This is now incompatible with older versions.  Users that previously used the openDbi method and passed a string, on a system where the default is not UTF-8, will now fail to open the database.  They should migrate to the byte[] variant, but no longer have access to the old system default behavior.

**Comment by scottcarey** [comment]
Ah, and lastly, the changes now on master have one thing I don't like:

`getDbiNames` returns null rather than an empty list when there are no names.

One other comment is that there should be some javadoc that indicates that this returns the keys from the default / null name Dbi,  so users that for users that are not using named databases it will return all of the keys in that Dbi which might cause OOM.

**Comment by krisskross** [comment]
> This is now incompatible with older versions. Users that previously used the openDbi method and passed a string, on a system where the default is not UTF-8, will now fail to open the database. They should migrate to the byte[] variant, but no longer have access to the old system default behavior.

Well, if they lost the old system default they can now use `getDbiNames` ;-)

> One other comment is that there should be some javadoc that indicates that this returns the keys from the default / null name Dbi, so users that for users that are not using named databases it will return all of the keys in that Dbi which might cause OOM.

Very valid point.

**Comment by scottcarey** [comment]
It is now possible to open all `Dbi`s without a-prioi knowledge of their names (or encodings, for that matter).

**Comment by benalexau** [comment]
> This is now incompatible with older versions. Users that previously used the openDbi method and passed a string, on a system where the default is not UTF-8, will now fail to open the database. They should migrate to the byte[] variant, but no longer have access to the old system default behavior.

Agreed. For the benefit of existing users who might be impacted by `Env.openDbi(String, DbiFlags...)` now explicitly using UTF-8, equivalent historical behaviour is now available by invoking `Env.openDbi("my original DBI name".getBytes(), DbiFlags...)`.
