### ISSUE TITLE
LMDB_0.9.20

### ISSUE THREAD

**Issue by krisskross** [lmdbjava/lmdbjava#43]
... is released.

**Comment by phraktle** [comment]
See [change log](http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob_plain;f=libraries/liblmdb/CHANGES)

**Comment by benalexau** [comment]
0.9.20 was withdrawn by the LMDB upstream project and they recommend to use 0.9.19. As such we have downgraded LmdbJava to 0.9.19. Further discussion in #46.
