### ISSUE TITLE
error using heap-allocated byte buffers

### ISSUE THREAD

**Issue by phraktle** [lmdbjava/lmdbjava#5]
When putting a heap allocated `ByteBuffer`, you get the following exception:

```
java.lang.ClassCastException: java.nio.HeapByteBuffer cannot be cast to sun.nio.ch.DirectBuffer
	at org.lmdbjava.ByteBufferProxy$UnsafeProxy.in(ByteBufferProxy.java:204)
	at org.lmdbjava.ByteBufferProxy$UnsafeProxy.in(ByteBufferProxy.java:166)
	at org.lmdbjava.Txn.keyIn(Txn.java:240)
	at org.lmdbjava.Dbi.put(Dbi.java:266)
```

**Comment by benalexau** [comment]
A direct buffer is always required. It's briefly mentioned in the tutorial ("We want to store some data, so we will need a direct ByteBuffer."), but I concede this is easily missed. Therefore I've added some improved error reporting so it's clearer what the issue is.

**Comment by phraktle** [comment]
I don't consider this a documentation / error message issue, but an actual problem: 1) the implementation goes against the type signature of the method (pretends to accept `ByteBuffer`, but only accepts `DirectBuffer`). 2) performance suffers since you force an extra copy operation when the original data lives on-heap (another reason why lmdbjava is slower than lmdbjni in our tests).

**Comment by krisskross** [comment]
This is for puts, right? You can use the reserve method to copy the data directly into the database and save that extra copy. Another option is to use Agrona's DirectBuffer to wrap the byte array. 

We could of course do Unsafe tricks for wrapped ByteBuffer byte arrays to fetch the address and such... but is it worth it?
