### ISSUE TITLE
Need option for creating a new keyVal in the Txn class

### ISSUE THREAD

**Issue by ChrisTrenkamp** [lmdbjava/lmdbjava#54]
As a user of lmdbjava, I want to use FlatBuffers to point directly to the LMDB database so I can access my data without allocating separate memory in the JVM.

[FlatBuffers](https://google.github.io/flatbuffers/) is a data exchange format that's much like ProtoBuf, but the key difference is it's zero-allocate/zero-parse.  When constructing a FlatBuffer object, you pass it a ByteBuffer object, making it quite nice to work with in lmdbjava.

The problem, however, is that the underlying keyVal field in the Txn object is reused.  If you assign a FlatBuffer object a ByteBuffer that is returned from a Txn, and then do the same to a different FlatBuffer object, they will both have the same values.  You could copy the bytes into memory, but that can severely damper the performance and memory usage of the program (especially for the kind of work I do).

Attached is a quick and dirty project demonstrating the problem.

[LMDBFlatBufferTest.zip](https://github.com/lmdbjava/lmdbjava/files/1038552/LMDBFlatBufferTest.zip)

**Comment by ChrisTrenkamp** [comment]
Well, this is embarrassing.  I just found the ByteBuffer.duplicate() method.

However, I would still like to know if the duplicate() method is creating a deep-copy of the entire buffer from the LMDB storage, or duplicating the pointer to the address in the LMDB memory and not copying the entire buffer.

**Comment by krisskross** [comment]
LMDB addresses are guaranteed to remain _within same_ `Txn`. And since `ByteBuffer.duplicate()` will copy the address/position/offset etc it should work according to you use case.

Note that you should never use a `ByteBuffer` outside the `Txn` unless you do a full copy of its contents.

```java
  @Test
  public void testCursorDuplicateByteBuffer() {
    final Dbi<ByteBuffer> db = env.openDbi(DB_1, MDB_CREATE);
    try (Txn<ByteBuffer> txn = env.txnWrite()) {
      try (Cursor<ByteBuffer> c = db.openCursor(txn)) {
        c.put(bb(1), bb(2));
        c.put(bb(3), bb(4));
      }
      txn.commit();
    }
    try (Txn<ByteBuffer> txn = env.txnRead()) {
      try (Cursor<ByteBuffer> c = db.openCursor(txn)) {
        c.first();
        ByteBuffer key1 = c.key().duplicate();
        ByteBuffer val1 = c.val().duplicate();

        c.last();
        ByteBuffer key2 = c.key().duplicate();
        ByteBuffer val2 = c.val().duplicate();

        assertThat(key1.getInt(0), is(1));
        assertThat(val1.getInt(0), is(2));

        assertThat(key2.getInt(0), is(3));
        assertThat(val2.getInt(0), is(4));
      }
    }
  }
```

**Comment by ChrisTrenkamp** [comment]
Thank you for the clarification (and the library, this is excellent).  Closing.
