### ISSUE TITLE
MVStore comparison

### ISSUE THREAD

**Issue by neilireson** [lmdbjava/lmdbjava#55]
Well done for the comparison, really helpful. However, it looks like you are not setting the MVStore to use off-heap memory, which will cause the OOME and also increase the need for GC as the data size grows.

**Comment by neilireson** [comment]
Sorry this should be in the Benchmark project. Also just looked at your MVStore code and it seems like your set up much as mine, so not sure why you're getting a OOME, my db regularly grows to several 100 GB.

**Comment by benalexau** [comment]
It could be many things: different versions of Java, different versions of MVStore, different treatment when running in a JMH harness versus an application, maybe the JMH benchmark overwhelming MVStore by making continuous requests without relief (and thus denying the JVM and/or some background MVStore process an opportunity for GC or other housekeeping that would be available with a non-batch, non-throughput workload).

I welcome pull requests in the benchmark project though if you can improve MVStore's performance.

Is it OK for us to close this ticket?

**Comment by neilireson** [comment]
Thanks for the reply. If I find some time I'll do a bit of hacking around to see if I can get MVStore to produce a comparative result. However being realistic this isn't going to happen for some time.
