### ISSUE TITLE
Cursor.seek() broken in v0.0.5?

### ISSUE THREAD

**Issue by realknorke** [lmdbjava/lmdbjava#57]
Maybe I found a bug in v0.0.5 which is not existent in v0.0.4 or v0.0.3.

Minimal example to reproduce the issue:

I created a minimal example [lmdbtest.tar.bz2 on gdrive](https://drive.google.com/open?id=0B9ZKlmZ8YOXBT0xKdV9rV0k3Mk0) (355kb)

This archive contains a simple maven project with one java class (to trigger the bug) and a directory 'lmdb' containing some example data. The lmdb database comes in memory mapped flavor (that is: <900kb of data in a 10GB sparse file! please don't fill your hd with zeros! ;)

Problem description:

In the given data I'm searching for the first entry (SeekOp.MDB_FIRST) which is successful, because the file is not empty.

But the buffer from Cursor.key() is empty and thus the buffer throws an exception on read() calls.

In version v0.0.4 this problem does NOT occur and the returned buffer is filled with 4 bytes (an integer, as expected).

Please uncompress (with sparse support!) and just import the maven project into your preferred IDE. Call the main() method. Change the pom.xml for v0.0.4 vs. v0.0.5

I hope you can reproduce the bug. If you need further details, please feel free to contact me.

I like lmdb and lmdbjava very much. I hope this issue helps you and don't waste your time.

**Comment by benalexau** [comment]
Is it possible to reproduce this bug with just a standalone JUnit test case? Could you also please confirm your platform and try it with the just-released LmdbJava 0.5.0?

**Comment by benalexau** [comment]
I'll close this ticket for now, as we really need a self-contained test case to explore how the database was created and written in order to troubleshoot this. It could be a corrupt file or other configuration issue. Please feel free to open a new ticket if you still find the problem occurs with LmdbJava 0.5.0 or above. Thanks.
