### ISSUE TITLE
add Dbi#close method

### ISSUE THREAD

**Issue by phraktle** [lmdbjava/lmdbjava#6]
Consider exposing `mdb_dbi_close` on `Dbi`.

Based on the [LMDB docs](http://lmdb.tech/doc/group__internal.html#ga52dd98d0c542378370cd6b712ff961b5) this is not necessary and potentially problematic if there are pending modifications, so not quite sure this is necessarily a good idea. But pointing it out for completeness.

**Comment by benalexau** [comment]
I agree it's not a good idea, but I've added it (along with lots of JavaDoc discouragement) just in case someone has an advanced reason to use it.
