### ISSUE TITLE
Delete db when drop

### ISSUE THREAD

**Issue by weidaru** [lmdbjava/lmdbjava#64]
Current implementation of Dbi.drop will not delete the db since the delete flag is set to 0.  This basically prevents a db ever being deleted unless I am missing some other methods. I wonder why the decision is made such. Wiping a database clearly seems to a common use case.

**Comment by benalexau** [comment]
[mdb_drop](http://www.lmdb.tech/doc/group__mdb.html#gab966fab3840fc54a6571dfb32b00f2db) as currently implemented by LmdbJava's `Dbi.drop(Txn)` method will delete the data from the database, but not delete the database or its handle.

As LMDB DBI slots are searched linearly and limited to the number specified at environment creation time, it is unusual to have large numbers of DBIs in a single environment. As such DBIs wouldn't generally be created and dropped routinely.

@krisskross do you have thoughts on whether we should support this? We can add an overloaded `drop(Txn, boolean)` easily enough and have the current `drop(Txn)` simply delegate to the new `boolean`-accepting method.

**Comment by krisskross** [comment]
Since LMDB have support for deleting a db it don't see why we shouldn't support it also. 

@benalexau I'm not sure how LMDB will respond if the only database is the unnamed database? Other than that I cannot see any quirky corner cases. Sounds like the way to go.

**Comment by weidaru** [comment]
I send a pull request here. https://github.com/lmdbjava/lmdbjava/pull/67
Please take a look.

**Comment by benalexau** [comment]
Closing this, as we'll move the conversation to the PR.
