### ISSUE TITLE
Incremental DB file growth for Windows

### ISSUE THREAD

**Issue by jubax** [lmdbjava/lmdbjava#68]
I'm currently using lmdbjava 0.6.0 which uses LMDB 0.9.19 (retrieved via Meta.version()).

When using Linux setting a large map size is no problem: The database file grows with the size of the database. This is convenient as I can just use a very large value and I don't have to care about database resizing.

When using Windows (I'm using Windows 7) the database file size is always the same as the mapping size. E.g. when I set a map size of 100GB then the file size will be 100GB, too.

The LMDB inventor says this behavior has been changed (ITS#8324). The corresponding commit seems to be

`fb5a768 Mon Nov 30 19:46:19 2015 ITS#8324 incremental DB file growth for Windows
`

which is from Nov. 30, 2016 and it should be included in LMDB 0.9.19.

However, the file size behavior under Windows still persists with lmdbjava 0.6.0. So I'm wondering:

- Did I misunderstand what ITS#8324 is supposed to do?
- Did lmdbjava bundle the wrong LMDB version?
- Or does the issue still exist in LMDB?

Any ideas?

**Comment by benalexau** [comment]
LmdbJava bundles LMDB version 0.19.1, which was built from the tag LMDB_0.9.19, commit 14cff072ec29f48093a9d40cc79934cf5376af4a.

While ITS#8324 shows up in several commits as per https://github.com/LMDB/lmdb/search?q=%22ITS%238324%22&type=Commits&utf8=%E2%9C%93 these do not appear to be included in the above tag or change log (or at least I can't see that with a quick search).

I see that LMDB 0.9.21 is now out, so I will log a new ticket to get LmdbJava updated to that version and we can see if that included the changes.

**Comment by jubax** [comment]
Thanks for the information. I will try out the new version when it will be released (going to vacation now, so it might take a few weeks before I can try it out).

**Comment by benalexau** [comment]
Issue #70 has updated LmdbJava to bundle LMDB 0.9.21.

**Comment by bluegol** [comment]
I had the same problem as OP did. Tried the latest lmdb snapshot which contains lmdb 0.9.21. Still had the problem. Tried replacing lmdbjava-native-windows-x86_64.dll in 0.6.0.jar. Didn't work either.

After some googling, I looked at lmdb revision graph. ( https://github.com/LMDB/lmdb/network ) It seems to me that several "ITS#8324" (cf. https://www.openldap.org/lists/openldap-bugs/201511/msg00060.html) fixes are committed but never really made it to the release. The commits are to the master branch, whereas the releases are from another branch.

I'm afraid I have to ask lmdb maintainer directly to resolve this issue (with not so much expectation, judging from the not so enthusiastic commit message).

**Comment by jubax** [comment]
Is there any progress so far? In case ITS#8324 will actually not be included in an official LMDB version, I'd suggest to build a patched version for lmdbjava. The commit seems to be a relatively small one and it affects only WIN32 sections of the code. Could this be an option for lmdbjava?

(Although I'm kind of wondering why this patch is not included in an official LMDB build as the author obviously already has spent the time of fixing this issue and it also does not affect LMDB on non-Windows operating systems.)

**Comment by bluegol** [comment]
No progress. I tried to send a post to the lmdb-technical mailing list (twice, actually), but the post didn't get through somehow.
I checked the official repo again, and checked the source code, to see if ITS#8324 was included. And the conclusion is no.

**Comment by benalexau** [comment]
> The commits are ONLY to the master branch, whereas the releases are from another branch.

I'd suggest asking on the lmdb-technical mailing list whether ITS#8324 can be merged into an LMDB tagged release. That way we can build it and include it in the LmdbJava distribution for you both. cc/ @hyc

> I'd suggest to build a patched version for lmdbjava. Could this be an option for lmdbjava?

Admittedly we could do this, but we prefer to only build official LMDB tagged releases. If something isn't merged into a tag release there's probably a reason for it.

> Tried replacing lmdbjava-native-windows-x86_64.dll in 0.6.0.jar.

FYI it is possible to use a custom built DLL by using the system properties provided in the [Library class](https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/Library.java). So if you need to build a custom version that's one way.

**Comment by hyc** [comment]
We left it out because there were some oddities with linking on Windows. Possibly the patch should be rewritten to use an explicit LoadLibrary/GetProcAddress sequence to avoid the issue. It's been low priority, but anyone interested is welcome to submit a patch...

**Comment by benalexau** [comment]
Thanks @hyc.

I'll close this ticket for now given it's best resolved by submitting a suitable patch to the upstream native library.

**Comment by jubax** [comment]
Thanks for this investigation and thanks to @hyc for the additional info about the LMDB patch. Hopefully someone having the same problem will find this thread and fix the issue in LMDB. (I might try sometime, but I do not have a lot of experience with C programming under Windows.)

**Comment by bluegol** [comment]
Well, I haven't programmed in windows C environment for a long time either, but I managed to merge commit [https://github.com/LMDB/lmdb/commits/5ef1908224] (which seems to be the last commit for ITS#8324), and it's running without trouble so far, in my use-case.
I don't think I can submit pull request with this, but in case anyone is interest, drop me a line blgl13.net a t    gmail d o t com.

**Comment by jubax** [comment]
BTW (just for completeness): When using MDB_WRITEMAP the performance on Windows seems to be much better when the incremental file growth patch is _not_ applied. See e.g.

https://www.openldap.org/lists/openldap-technical/201512/msg00194.html

(My tests also confirm this.)

So for my use case (which involves very large write transactions) ITS#8324 is actually not a good idea.

**Comment by vladp** [comment]
It seems like on Windows platform, this still continuous to be a limitation.

".. When using Windows (I'm using Windows 7) the database file size is always the same as the mapping size. E.g. when I set a map size of 100GB then the file size will be 100GB, too. .."

I am on windows 10 , using LMDBJava 0.6.1.
Are there workaround, by any chance, developed for this windows-only issue?

I am storing images in LMDB (of over 3mb in size each) -- so I am reaching this problem rather quickly.

thx
