### ISSUE TITLE
How do I set the map size after the creation of the Env?

### ISSUE THREAD

**Issue by jubax** [lmdbjava/lmdbjava#69]
At startup I create a Env via something like:

`Env.create(ByteBufferProxy.PROXY_OPTIMAL).setMapSize(10_000_000);
`

However, in case I want to change the map size (e.g. in order to work around the Windows file size issue) I cannot do

`Env.setMapSize();
`

Currently I'm closing the Env and I recreate it with a larger map size (which works fine). I'm just wondering if there is an API call missing or if I just overlooked the correct method?

**Comment by benalexau** [comment]
LmdbJava only offers the `Env.Builder` mechanism to resize the map. The [C API notes](http://www.lmdb.tech/doc/group__mdb.html#gaa2506ec8dab3d969b0e609cd82e619e5) offers more information on how this works.

**Comment by jubax** [comment]
Okay, thanks for the explanation. lmdbjava provides a really nice, clean API on top of LMDB, so I was just curious.
