### ISSUE TITLE
Update to LMDB C 0.9.21

### ISSUE THREAD

**Issue by benalexau** [lmdbjava/lmdbjava#70]
https://github.com/LMDB/lmdb/tree/LMDB_0.9.21 tag now exists and has for ~3 months. 

@krisskross should we update (I'm cautious after 0.9.20 being withdrawn)?

**Comment by krisskross** [comment]
The release seems fine even tough it doesn't have a lot in it. I'd say we can wait until it's requested by users.

**Comment by krisskross** [comment]
Wops, read issues in the wrong order. Yeah lets upgrade then.

**Comment by benalexau** [comment]
Resolved in commit 52f07990788b08f753eaf9f38ec5feba5f650022.
