### ISSUE TITLE
Release 0.6.1 to Maven Central

### ISSUE THREAD

**Issue by nktpro** [lmdbjava/lmdbjava#73]
I've been testing 0.6.1-SNAPSHOT and it's been stable for us. Since it has the latest LMDB 0.9.21 upgrade and the fixes are quite important, would you consider publishing the release?

**Comment by benalexau** [comment]
For at least a decade I've had a "no known bugs at the time of a release" rule, so I need to get #72 fixed first. Please feel free to submit a patch if you like.

**Comment by benalexau** [comment]
#72 has been fixed - along with several other improvements - so we are ready to release 0.6.1. I'll just give it a few days for people to try 0.6.1-SNAPSHOT and report any possible regressions.

**Comment by kaandok** [comment]
Is it possible to bundle LMDB 0.9.22 with the 0.6.1 release?

**Comment by benalexau** [comment]
Released 0.6.1. Related links:

* [Change log](https://github.com/lmdbjava/lmdbjava/wiki/Change-Log#061-25-apr-2018)
* Travis [deployment log](https://travis-ci.org/lmdbjava/lmdbjava/jobs/370869707)
* Maven Central [0.6.1 directory](http://repo1.maven.org/maven2/org/lmdbjava/lmdbjava/0.6.1/)

**Comment by nktpro** [comment]
@benalexau Thank you for all your work on this project!

**Comment by kaandok** [comment]
@benalexau many thanks!
