### ISSUE TITLE
Possible for user to pass in transaction to Env.openDbi?

### ISSUE THREAD

**Issue by devinrsmith** [lmdbjava/lmdbjava#74]
Are there any technical reasons why `Txn` isn't part of the `Env.openDbi` signature?

**Comment by benalexau** [comment]
There is no technical reason that required `Txn` to be created within the `Env` method, with the choice primarily being one to improve ergonomics by relieving users from needing to distinguish between read-only and read-write transactions (both of which need to be committed to finalise the `Dbi`) and the low frequency, cold path nature of such calls.

Did you have a situation where you'd like to present a `Txn`? I'm cautious around adding more overloaded methods that accept a `Txn` in light of the overloaded versions for `Comparator` support. However refactoring suggestions are welcome etc,

**Comment by benalexau** [comment]
Was there any further comments on this or can we close it?

**Comment by devinrsmith** [comment]
Sorry, I haven't been actively working with LMDB recently. I believe there was a situation where I wanted to create multiple DBs with the same transaction, but I don't remember exactly. I'll close this, and revisit in the future if necessary. Thanks.
