### ISSUE TITLE
Multiple Env instances not respecting write lock?

### ISSUE THREAD

**Issue by devinrsmith** [lmdbjava/lmdbjava#75]
I was under the impression that LMDB only allowed one write lock at any given time, even across multiple threads / processes. I've got a program that seems to demonstrate that two threads are getting two write locks at the same time.

https://gist.github.com/devinrsmith/c01ea812aed270ed6118c41ec124fe16

About half the time the program exits with "done - this might indicate a bug", which I don't think should ever happen. I've been able to reproduce this on OS X and Debian.

Am I using `Env` incorrectly?

**Comment by phraktle** [comment]
Hi @devinrsmith,

Indeed, this is invalid usage. As the [LMDB docs](http://www.lmdb.tech/doc/) state:

> Do not have open an LMDB database twice in the same process at the same time. Not even from a plain open() call - close()ing it breaks flock() advisory locking.

**Comment by devinrsmith** [comment]
Ah! Earlier in the doc it's a little misleading:

> The library is fully thread-aware and supports concurrent read/write access from multiple processes and threads.

I assumed that meant the same process could even open it up multiple times concurrently... thanks for the clarification.
