### ISSUE TITLE
Env, AutoCloseable and abstraction

### ISSUE THREAD

**Issue by jbee** [lmdbjava/lmdbjava#78]
This is somewhere between feedback and a question. Or I just miss something.

Currently creating and using an `Env` requires proper error handling via try-resource (`AutoCloseable`).
At the same time I would like to hide the details of "the database" so I have a data access abstraction.

It is my understanding that the `Env` is typically opened at application startup and closed on application shutdown. So the resource is used roughly for the lifetime of the application. 

I see two ways to have my abstraction:

1. I make it `AutoCloseable` too, so it is treated as the "resource" and it in turn will close the `Env` underneath.
2. I don't use `Env` for the lifetime of the application but create it when needed. This basically means per request, what feels wrong, but who knows...

So my question is: Is there any way `Env` does not need to be a resource that requires `AutoCloseable`? Because this cascades upwards trough the application right up to the "main" what feels kind of ugly. 
Maybe it is "good enough" to have a "destructor" cleanup what needs to be cleaned for `Env`?
Everyone who has a reference to `Env` could continue to close it explicitly but if not `Env` would take care of itself? Is something like that possible?

Or is it reasonable to start with creating an `Env` for each request?
Or is there another way to handle `Env` that does not cascade/leaks `AutoCloseable` beyond abstractions?

**Comment by benalexau** [comment]
My own classes that create an `Env` simply implement `AutoCloseable`. This `Env` (and indeed `Dbi` instances obtained from it) is used for the duration of the application.

By way of comparison with the closest JDBC equivalent class, [Connection](https://docs.oracle.com/javase/9/docs/api/java/sql/Connection.html) also implements `AutoCloseable`. The motivation for `AutoCloseable` is summarised in the [Better Resource Management with Java SE 7](http://www.oracle.com/technetwork/articles/java/trywithresources-401775.html) as follows:

> The typical Java application manipulates several types of resources such as files, streams, sockets, and database connections. 

As `Env` encapsulates a file-based database connection, it would appear fairly well-aligned with the above purpose of `AutoCloseable`. I suspect most applications use a [dependency injection provider](https://github.com/akullpp/awesome-java#dependency-injection) to automatically create singletons like `Env`, inject them, and close them during shutdown.

Did you have any particular suggestions on how we might improve this? I can see we could introduce an `EnvApi` that holds most of the current `Env` (without `AutoCloseable`), `Env` would extend `EnvApi` but implement `AutoCloseable`, `Env.Builder.open(..)` would return `Env` and `Env.Builder.openApi(..)` would return `EnvApi`. However it feels pretty confusing just to give people the option of not using `AutoCloseable` plus we'd lose the `final` modifier (as `EnvApi` needs to be `public` for third party use but non-`final` so `Env` can extend it, or tackle a broader refactor which will impact existing user code).

@krisskross did you have any comments on this?

**Comment by jbee** [comment]
I don't doubt that the use of `AutoCloseable` is aligned with its purpose as described. I just don't like the code it causes.

In contrast to all the other use cases a DB connection is a resource that has a long lifetime and this is where it gets ugly in the code since there cannot be a single enclosed piece of code. The point of creation must be somewhere "early" with application lifetime. But the point of usage can be some 3-5 components down from there, in which case all of these in some sense "wrap" the resource and would need to implement `AutoCloseable` and delegate `close()` down the line what is really ugly.

An alternative is to break abstraction at the top level. Do the try-resource there with something warping the  `Env` directly and "inject" or "deliver" that wherever we want to use it. I almost like that better even if it forces us to always have this wrapper even though another setup might not need such a part at all in which case we would implement it with a "NOOP implementation" so we could have our try-resource block on top level. 

I was hoping that the `Env` could be freed of the need to have its user explicitly call a `close()`. But I have no clue what LMDB underneath requires us to do. I was just thinking that if we have the instance of the lifespan of the application anyway why not "close" it when the application ends by a "automatic destructor". Somewhat has the same effect at roughly the same moment.

I agree that the `EnvApi` is confusing. Wound not want that.

**Comment by krisskross** [comment]
Why not use a [shutdown hook](https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#addShutdownHook(java.lang.Thread)) that call `close` when the application terminates? It could be registered by the data access abstraction itself at construction. Or maybe have some life cycle registry where objects can register themselves for cleanup.

**Comment by jbee** [comment]
That would solve it for me but everyone else would have the same problem. `AutoCloseable` is the obvious choice but it creates trouble for the library users. I wanted to point that out for you especially because it is the obvious choice. Does it have to be this way? Would it be so bad have the library use a shutdown hook internally so the library users are free of handling this situation? Purely because that would be a nicer API to work with.

If users usually use a shutdown hook because it is the most convenient way to ensure the `Env` is closed it effectively means they don't make use of `AutoCloseable` but "manually" close it. In addition they get a warning about a potential leak since they don't use a try-with-resource block.

**Comment by krisskross** [comment]
Yes, @benalexau and me discussed many times about how much convenience to put in the library. Its a tough one. We actually started out with an implementation that looked pretty far from the original LMDB API. But after a while the (maybe "boring") conclusion was to stay true to the original API as much as possible without too many bells and whistles. That's probably what most users would expect from the library. And it doesn't prohibit anyone from building abstractions on top of it.

So while I agree with your reasoning - i'm not sure if this kind of life cycle management belongs in this library. We could always create a lmdbjava++ project under the lmdbjava umbrella but maybe not in lmdbjava core... 

Please correct me if i'm wrong @benalexau.

**Comment by jbee** [comment]
If you think the lifecycle of `Env` is one that should be managed I fully agree to keep it minimal and have the user do that job. I just was unsure how useful it would be to actually "manage" `Env`s lifecycle if it always lives and dies with the application anyway. In that case why not hide that there is something to manage? I don't think this bit of convenience is worth wrapping around by another project. It was a thought for a possible improvement. If you see use cases that render it invalid my question is answered.

**Comment by krisskross** [comment]
I think it would be difficult to implement this functionality correctly without knowing how the application itself behaves, i.e. the startup and shutdown ordering sequence for its internal part. For example - if we close the `Env` too early and the application later tries to write to it - a segmentation fault will terminate the application without any possibility for further cleanup. We also must make sure to close it after all transactions/database etc have been closed.

We could probably come up with something clever, but the complexity already seems to overshadow the convenience of the functionality. Here's the docs for [mdb_env_close](http://www.lmdb.tech/doc/group__mdb.html#ga4366c43ada8874588b6a62fbda2d1e95).

**Comment by jbee** [comment]
This kind of clever is no good. We should close this issue before anyone changes their mind.

**Comment by krisskross** [comment]
Alright, sounds like we're in agreement. I'll let @benalexau get a chance to reply, otherwise we'll close it.

**Comment by benalexau** [comment]
I believe that automatic `Env.close()` is undesirable when you consider the risk of SIGSEGV if incorrectly timed and the need to accommodate advanced deployment situations (eg multi-tenancy deployments, special classloader configurations like OSGi, "plugin" systems etc).

Nevertheless users happy to rely on a DI container or similar to automatically create and close the `Env` (perhaps guaranteeing to close it after closing all instances that depended on it and those instances not closing if they have in-flight operations etc) can use the existing class hierarchy. For example, a factory might look like this:

```java
public final class EnvFactory<T> implements Closeable {

  private final Env<T> env;

  public EnvFactory(final Env.Builder<T> builder, final File path) {
    this.env = builder.open(path, MDB_NOSUBDIR);
  }

  @Override
  public void close() {
    env.close();
  }

  public Env<T> getEnv() {
    return env;
  }

}
```

The resulting `Env` can then be injected into a client class such as this:

```java
 */
public final class EnvUser {

  private final Env<DirectBuffer> env;

  public EnvUser(Env<DirectBuffer> env) {
    this.env = env;
  }
  
  public void useIt() {
    env.getDbiNames();
  }
  
}
```

Neither of the example classes above present errors or warnings that I've noticed. As such I believe users just wanting to get an `Env` handle and rely on something else to manage its shutdown should be OK.

If I'm missing something here please let me know. We'd like to ensure that LmdbJava does not impose inappropriate ergonomics on users.

**Comment by jbee** [comment]
The "trick" seams to be to not assign a `AutoCloseable` to a local variable (without a try-with-resource). That would give you a warning. Assigning it to a field is fine.

**Comment by benalexau** [comment]
> Assigning it to a field is fine.

Are we OK to now close this ticket?
