### ISSUE TITLE
Bulk insert of ordered/unordered keys?

### ISSUE THREAD

**Issue by foror** [lmdbjava/lmdbjava#79]
I read the TutorialTest and JavaDoc, but I still don't have ideas how to correctly make bulk insert of ordered/unordered keys. It's common use case and I think this should be added to the documentation.

**Comment by krisskross** [comment]
There's nothing special about "bulk" insertions. Its just multiple `put` operations committed in same `Txn` and LMDB handles key ordering for you.

**Comment by benalexau** [comment]
I'd also suggest considering whether your bulk insert pattern could use specific `DbiFlags` or `PutFlags.MDB_APPEND`. These will improve insertion performance and significantly reduce the size of the resulting file. When benchmarking this please be mindful that small tests are unlikely to reflect the overhead of tree rebalancing, cache misses and disk seeks. As such I'd suggest making the database at least as large as RAM before you start trying the different flags and write patterns.

**Comment by benalexau** [comment]
As it's been two months since the last message, I'll close this ticket now. Feel free to open a new one if there's a specific query we can assist with.
