### ISSUE TITLE
Core dump on reading object pulled out of lmdbjava

### ISSUE THREAD

**Issue by davidwynter** [lmdbjava/lmdbjava#80]
I have been running lmdbjava on my dev server for 7 months. But today for the first time I got a core dump. Here is the code:

    	public LoginDetail getDemoUserLogin(String ikey) {
		final ByteBuffer key = allocateDirect(40);
		key.put(ikey.getBytes(UTF_8)).flip();
		LoginDetail logDtl = null;
		try (Txn<ByteBuffer> txn = demoenv.txnRead()) {
			final ByteBuffer found = demoUserLogin.get(txn, key);
			// The fetchedVal is read-only and points to LMDB memory
			final ByteBuffer fetchedVal = txn.val();
			if (fetchedVal.remaining() == 0) {
				txn.close();
				return null;
			}
			logDtl = (LoginDetail) toObject(fetchedVal);
			txn.close();
		} catch (ClassNotFoundException e) {
			logger.error("getDemoUserLogin LoginDetail class not found", e);

		} catch (IOException e) {
			logger.error("getDemoUserLogin IOException", e);

		}
		return logDtl;
	}

    	public static Object toObject(ByteBuffer byteBuffer) throws IOException, ClassNotFoundException {
		byte[] bytes = new byte[byteBuffer.remaining()];
		byteBuffer.get(bytes);
		Object obj = null;
		ByteArrayInputStream bis = null;
		ObjectInputStream ois = null;
		try {
			bis = new ByteArrayInputStream(bytes);
			ois = new ObjectInputStream(bis);
			obj = ois.readObject();
		} finally {
			if (bis != null) {
				bis.close();
			}
			if (ois != null) {
				ois.close();
			}
		}
		return obj;
	}

Here is the relevant part of the core dump:

    Stack: [0x00007fed715dc000,0x00007fed716dd000],  sp=0x00007fed716d8818,  free space=1010k
    Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
    C  [libc.so.6+0x14dc36]
    C  [libzip.so+0x12c7f]  ZIP_GetEntry2+0xff
    C  [libzip.so+0x3ec0]  Java_java_util_zip_ZipFile_getEntry+0xf0
    J 145  java.util.zip.ZipFile.getEntry(J[BZ)J (0 bytes) @ 0x00007feda115340e [0x00007feda1153340+0xce]
    J 1671 C2 java.util.zip.ZipFile.getEntry(Ljava/lang/String;)Ljava/util/zip/ZipEntry; (101 bytes) @ 0x00007feda15a3bb0 [0x00007feda15a3820+0x390]
    J 1686 C2 java.util.jar.JarFile.getEntry(Ljava/lang/String;)Ljava/util/zip/ZipEntry; (22 bytes) @ 0x00007feda159f41c [0x00007feda159f3e0+0x3c]
    J 1057 C2 sun.misc.URLClassPath$JarLoader.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; (85 bytes) @ 0x00007feda13e0104 [0x00007feda13e0080+0x84]
    J 1059 C2 sun.misc.URLClassPath.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; (83 bytes) @ 0x00007feda13f76a0 [0x00007feda13f7580+0x120]
    J 447 C1 java.net.URLClassLoader$1.run()Ljava/lang/Class; (63 bytes) @ 0x00007feda125ce6c [0x00007feda125cc60+0x20c]
    J 432 C1 java.net.URLClassLoader$1.run()Ljava/lang/Object; (5 bytes) @ 0x00007feda1253514 [0x00007feda1253480+0x94]
    v  ~StubRoutines::call_stub
    V  [libjvm.so+0x693e76]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1056
    V  [libjvm.so+0x72d14c]  JVM_DoPrivileged+0x27c
    J 168  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedExceptionAction;Ljava/security/AccessControlContext;)Ljava/lang/Object; (0 bytes) @ 0x00007feda115f5d5 [0x00007feda115f500+0xd5]
    J 2595 C2 java.net.URLClassLoader.findClass(Ljava/lang/String;)Ljava/lang/Class; (47 bytes) @ 0x00007feda186d5b8 [0x00007feda186d520+0x98]
    j  java.lang.ClassLoader.loadClass(Ljava/lang/String;Z)Ljava/lang/Class;+70
    J 440 C1 sun.misc.Launcher$AppClassLoader.loadClass(Ljava/lang/String;Z)Ljava/lang/Class; (85 bytes) @ 0x00007feda1256e14 [0x00007feda1256460+0x9b4]
    J 439 C1 java.lang.ClassLoader.loadClass(Ljava/lang/String;)Ljava/lang/Class; (7 bytes) @ 0x00007feda125605c [0x00007feda1255f40+0x11c]
    v  ~StubRoutines::call_stub
    V  [libjvm.so+0x693e76]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1056
    V  [libjvm.so+0x694381]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x321
    V  [libjvm.so+0x6947d6]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Handle, Thread*)+0x56
    V  [libjvm.so+0xa40db0]  SystemDictionary::load_instance_class(Symbol*, Handle, Thread*)+0x3f0
    V  [libjvm.so+0xa3fcfc]  SystemDictionary::resolve_instance_class_or_null(Symbol*, Handle, Handle, Thread*)+0x78c
    V  [libjvm.so+0xa411d3]  SystemDictionary::resolve_or_fail(Symbol*, Handle, Handle, bool, Thread*)+0x33
    V  [libjvm.so+0x71251e]  find_class_from_class_loader(JNIEnv_*, Symbol*, unsigned char, Handle, Handle, unsigned char, Thread*)+0x3e
    V  [libjvm.so+0x719121]  JVM_FindClassFromCaller+0x2e1
    C  [libjava.so+0xe320]  Java_java_lang_Class_forName0+0x130
    J 680  java.lang.Class.forName0(Ljava/lang/String;ZLjava/lang/ClassLoader;Ljava/lang/Class;)Ljava/lang/Class; (0 bytes) @ 0x00007feda12f1974 [0x00007feda12f1880+0xf4]
    J 728 C1 java.lang.Class.forName(Ljava/lang/String;ZLjava/lang/ClassLoader;)Ljava/lang/Class; (53 bytes) @ 0x00007feda130f00c [0x00007feda130eaa0+0x56c]
    j  java.io.ObjectInputStream.resolveClass(Ljava/io/ObjectStreamClass;)Ljava/lang/Class;+10
    j  java.io.ObjectInputStream.readNonProxyDesc(Z)Ljava/io/ObjectStreamClass;+108
    j  java.io.ObjectInputStream.readClassDesc(Z)Ljava/io/ObjectStreamClass;+86
    j  java.io.ObjectInputStream.readOrdinaryObject(Z)Ljava/lang/Object;+22
    j  java.io.ObjectInputStream.readObject0(Z)Ljava/lang/Object;+401
    j  java.io.ObjectInputStream.readObject()Ljava/lang/Object;+19
    j  uk.co.example.quokka.LmDbStore.toObject(Ljava/nio/ByteBuffer;)Ljava/lang/Object;+41

I'd like to better understand why this is happening, as I need to prevent this happening if possible before we go to production.  It may not have anything to do with lmdbjava? The stored objects have not changed class structure.

**Comment by krisskross** [comment]
Looks like a class loader problem. There are quite recent bug reports on Java 8 that looks similar to your core dump.

https://bugs.openjdk.java.net/browse/JDK-8191484
https://bugs.openjdk.java.net/browse/JDK-8175970

**Comment by davidwynter** [comment]
Thank you!
