### ISSUE TITLE
atMost/atLeast+backwards iterator behavior

### ISSUE THREAD

**Issue by alepar** [lmdbjava/lmdbjava#83]
[code link](https://github.com/lmdbjava/lmdbjava/blob/2b307006b5b656f7199f4f31077cacc713848983/src/test/java/org/lmdbjava/CursorIteratorTest.java#L109)
`verify(atMostBackward(bb(5)), 8, 6);`
vs
`verify(atMost(bb(5)), 2, 4);`

Is this really the intended behavior? I would naively expect, that iterating backwards would produce the same result set, just in the different order?

**Comment by benalexau** [comment]
I believe so.

The database contains values 2, 4, 6, 8.

> verify(atMostBackward(bb(5)), 8, 6);

If you iterate backwards it would be 8, 6, 4, 2. If you iterate backwards but the greatest allowed value is 5, you'd get 8 and 6. That's what is shown in the test.

> verify(atMost(bb(5)), 2, 4);

If you iterate forwards it would be 2, 4, 6, 8. If you iterate forwards but the greatest allowed value is 5, you'd get 2 and 4. That's what is shown in the test.

**Comment by alepar** [comment]
I guess I'm confused why atMostXXX(n) KeyRange represents either values smaller or greater than n depending on XXX (shouldn't it be independent of XXX?).
But, if you think this is intended, then I'm not going to argue, just wanted to point this one out.

**Comment by benalexau** [comment]
All `atMost[.*]` method signatures accept a `stop` parameter. So what you're passing is when the iterator must stop after iterating in whichever order was indicated by the method name.

For example `atMostBackward(5)` means iterate backward over the data but stop on value 5. `atMost(5)` means iterate forward over the data but stop on value 5.

Does that make more sense?
