### ISSUE TITLE
KeyRange.atLeast vs KeyRange.atLeastBackward with out-of-bound value

### ISSUE THREAD

**Issue by creambun** [lmdbjava/lmdbjava#86]
Hi there,

I am not sure if the behavior described below is as expected because I cannot yet find relevant document. If there is, please kindly let me know

The behavior I found is that KeyRange.atLeast can iterate over all records even if the given key range value is smaller than the key of the first record, while KeyRange.atLeastBackward cannot even iterate one record if the given key range value is greater than the key of the last record. It is best illustrated below:

Data in db: {2, "22"}, {4, "44"}, {6, "66"}, {8, "88"}
Search with KeyRange.atLeast and start with key = 1 -> all records can be iterated. I have no question about this
Search with KeyRange.atLeast and start with key = 2 -> all records can also be iterated. I have no question about this
Search with KeyRange.atLeastBackward and start with key = 8 -> all record can be iterated backward. I have no question about this either
Search with KeyRange.atLeastBackward and start with key = 9 -> no record can be iterated. I am quite surprised

Can anyone please give me some hint / help? Thanks

JUnit test code can be found in the attached file test.zip

[test.zip](https://github.com/lmdbjava/lmdbjava/files/1912830/test.zip)

**Comment by benalexau** [comment]
Thanks for confirming the test passes with 0.6.1-SNAPSHOT.

I will release 0.6.1 properly within the next few days. Please watch issue #73 for updates. The main outstanding task is updating the LMDB C version, although I am also likely to update some build plugin versions as well for unrelated reasons.
