### ISSUE TITLE
Update to LMDB C 0.9.22

### ISSUE THREAD

**Issue by benalexau** [lmdbjava/lmdbjava#88]
Tag: https://github.com/LMDB/lmdb/tree/LMDB_0.9.22

Requested by @kaandok for inclusion in LmdbJava 0.6.1 via #73.

@krisskross do you think we should update?

**Comment by krisskross** [comment]
Sorry for the late reply. Yes sounds like a good idea.

**Comment by benalexau** [comment]
Released as version 0.9.22-2 due to [issues](https://github.com/lmdbjava/native/commit/edf201ba0e155b0d51a15f53642a9e0d0354891d) with Travis and GPG versions. Now in Maven Central:

http://repo1.maven.org/maven2/org/lmdbjava/lmdbjava-native-linux-x86_64/0.9.22-2/
http://repo1.maven.org/maven2/org/lmdbjava/lmdbjava-native-windows-x86_64/0.9.22-2/
http://repo1.maven.org/maven2/org/lmdbjava/lmdbjava-native-osx-x86_64/0.9.22-2/
