### ISSUE TITLE
testcase for check the total DB size in DB

### ISSUE THREAD

**Issue by JayT106** [lmdbjava/lmdbjava#91]
Just wandering does lmdbjava has any testcase for checking the ratio for the write-in key value data and the data on the disk ? I tried to integrate this DB to my project and did some test, the testcase like this: want to write 1K key/value into DB (call 1K put method), each key equal to 16B, value equal to 100B, total raw size should be 0.116M, but the actual db size in the disk is 20MB. Do I use wrong db settings?

this is the db env settings
```
        env = create().setMapSize(1L << 40).setMaxDbs(2).setMaxReaders(8).open(f);

        try {
            db = env.openDbi(name, MDB_CREATE);
        } catch (Exception e1) {
            LOG.error("Failed to open the database " + this.toString() + " due to: ", e1);
            if (e1.getMessage().contains("No space left on device")) {
                LOG.error("Shutdown due to lack of disk space.");
                System.exit(0);
            }

            // close the connection and cleanup if needed
            close();
        }
```

the put method in my db wrap class like this
```
public void put(byte[] k, byte[] v) {
        check(k);
        check();

        if (v == null) {
            db.delete(allocateDirect(k.length).put(k).flip());
        } else {
            db.put(allocateDirect(k.length).put(k).flip(), allocateDirect(v.length).put(v).flip());
        }
    }
```

**Comment by benalexau** [comment]
It's to do with LMDB page sizes. As noted in the [LmdbJava Benchmark discussion](https://github.com/lmdbjava/benchmarks/blob/master/results/20160710/README.md#test-2-determine-24816-kb-byte-values):

> If storage space is an issue, it is important that entry sizes reflect LMDB's page sizing requirements. In summary its optimal entry sizes are (in bytes) 2,030, 4,084, 8,180, 12,276 and so on in 4,096 byte increments.

**Comment by krisskross** [comment]
Closing inactive.
