### ISSUE TITLE
multiple database or multiple environments?

### ISSUE THREAD

**Issue by lfoppiano** [lmdbjava/lmdbjava#92]
Hi I have a question I didn't really find much about it. Do you think it is better/advisable to instantiate one single environment and as many databases as needed, or instantiate one database per environment. 

What is the general opinion? 

Thank you in advance
Luca

**Comment by benalexau** [comment]
One `Env`, many `Dbi`s. At a practical level if your `Txn`s need to be atomic and isolated across multiple `Dbi`s that's your simplest option anyway (`Txn`s are owned by a particular `Env`, not the `Dbi`).

**Comment by lfoppiano** [comment]
I see, if I undersrtand correctly then sharing a `Txn` among several databases belonging from different `Env`s should not work or is just bad practices?

**Comment by krisskross** [comment]
Don't do it. You'll probably SIGSEGV argumenting `Env` with a `Tx` it did not originate from.

**Comment by krisskross** [comment]
Closing inactive.
