### ISSUE TITLE
Maven build issues

### ISSUE THREAD

**Issue by nwbrad** [lmdbjava/lmdbjava#95]
I apologize in advance if this is a result of me doing something wrong, I'm relatively new to Java and have been using LMDB under nodejs and now I want to work with Java..

I cloned the lmdbjava repository
then changed to the appropriate directory and ran
**mvn clean package**

It runs fine for a while, then hangs on  org.lmdbjava.EnvTest.

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.lmdbjava.LibraryTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.507 s - in org.lmdbjava.LibraryTest
[INFO] Running org.lmdbjava.CursorIteratorTest
[INFO] Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.902 s - in org.lmdbjava.CursorIteratorTest
[INFO] Running org.lmdbjava.CursorParamTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.242 s - in org.lmdbjava.CursorParamTest
[INFO] Running org.lmdbjava.TxnTest
[INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.065 s - in org.lmdbjava.TxnTest
[INFO] Running org.lmdbjava.CursorTest
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.233 s - in org.lmdbjava.CursorTest
[INFO] Running org.lmdbjava.MaskedFlagTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in org.lmdbjava.MaskedFlagTest
[INFO] Running org.lmdbjava.TutorialTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.903 s - in org.lmdbjava.TutorialTest
****[INFO] Running org.lmdbjava.EnvTest   <=== Hangs here and never completes.****

I'm running on CentOS Linux release 7.5.1804  
Java:
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
Maven:
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T11:49:05-08:00)
Maven home: /usr/local/share/apache-maven
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-8.b10.el7_5.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-862.3.3.el7.x86_64", arch: "amd64", family: "unix"

Any ideas on where I went wrong or what to check.
Thanks in advanced for your help.

**Comment by nwbrad** [comment]
I reran it and just let it sit.  In finished the EnvTest in about 10 minutes and the .DbiTest in 1 hour 24 minutes...  I imagine those times are not correct or reasonable.  It finished ComparatorTest with the following error:
Running org.lmdbjava.ComparatorTest
Jun 21, 2018 8:04:02 PM io.netty.util.ResourceLeakDetector reportTracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.

Below is the remainder of the output:

[INFO] Running org.lmdbjava.EnvTest
Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, **Time elapsed: 598.914 s** - in org.lmdbjava.EnvTest
[INFO] Running org.lmdbjava.ByteBufferProxyTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.227 s - in org.lmdbjava.ByteBufferProxyTest
[INFO] Running org.lmdbjava.ResultCodeMapperTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in org.lmdbjava.ResultCodeMapperTest
[INFO] Running org.lmdbjava.MetaTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.lmdbjava.MetaTest
[INFO] Running org.lmdbjava.DbiTest
[INFO] Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: **5,080.821 s** - in org.lmdbjava.DbiTest
[INFO] Running org.lmdbjava.ComparatorTest
Jun 21, 2018 8:04:02 PM io.netty.util.ResourceLeakDetector reportTracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
        org.lmdbjava.ByteBufProxy.<clinit>(ByteBufProxy.java:59)
        org.lmdbjava.CursorParamTest$NettyBufferRunner.<init>(CursorParamTest.java:290)
        org.lmdbjava.CursorParamTest.data(CursorParamTest.java:84)
        sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        java.lang.reflect.Method.invoke(Method.java:498)
        org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        org.junit.runners.Parameterized.allParameters(Parameterized.java:280)
        org.junit.runners.Parameterized.<init>(Parameterized.java:248)
        sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
        org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
        org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
        org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
        org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:362)
        org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
        org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
        org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
[INFO] Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.065 s - in org.lmdbjava.ComparatorTest
[INFO] Running org.lmdbjava.KeyRangeTest
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.lmdbjava.KeyRangeTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 180, Failures: 0, Errors: 0, Skipped: 0
.
.
.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:35 h
[INFO] Finished at: 2018-06-21T20:04:18-07:00
[INFO] ------------------------------------------------------------------------
##################################################################################################################################################################

So, it did build it successfully, but I have to wonder if there is a compatibility issue with the version of Java or Maven I'm running....

**Comment by krisskross** [comment]
Interesting. Sounds like something that you might want to raise on the OpenLDAP mailing list. We dont do any CentOS tests as far as i know.

**Comment by krisskross** [comment]
Seems possible to run travis with CentOS using docker builds. We don't have that ATM. Would you like to give it a try?

**Comment by benalexau** [comment]
Did you ever sort this out? Are you running in a virtual machine or other environment with low levels of available memory? Maybe next time the test is running load up [VisualVM](https://visualvm.github.io/) and see if it offers any clues. There are many other ways to look at what the JVM is doing at runtime (eg `jstack`) but this is probably the simplest starting point.

**Comment by benalexau** [comment]
Closing as this ticket is very old and there's not much we can do without additional information. Please feel free to open a new ticket if needed.
